.login-page[hidden],.app[hidden]{display:none!important}
.inactive-ad{opacity:.62;background:#f5f5f5}.ad-switch{display:grid;grid-template-columns:38px auto;align-items:center;gap:2px 7px;font-size:10px;font-weight:800;cursor:pointer}.ad-switch input{display:none}.ad-switch i{width:38px;height:22px;border-radius:20px;background:#bbb;position:relative}.ad-switch i:after{content:'';position:absolute;width:16px;height:16px;border-radius:50%;background:#fff;left:3px;top:3px;transition:.2s}.ad-switch input:checked+i{background:#25a65a}.ad-switch input:checked+i:after{left:19px}.ad-switch span{grid-column:1/-1;text-align:center;color:#666}
.nav{padding:9px 11px;display:flex;align-items:center;gap:11px}
.nav i{font-style:normal;width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:#292929;color:#fff;font-size:17px}
.nav.active i,.nav:hover i{background:#111;color:var(--yellow)}.nav span{margin-left:0}
.date-filter{display:flex;align-items:end;gap:10px;flex-wrap:wrap;background:#fff;border:1px solid #eee;border-radius:18px;padding:13px;margin-bottom:16px}
.date-filter select,.date-filter input{border:1px solid #ddd;border-radius:11px;background:#fafafa;padding:10px;font:inherit}
.date-filter label{font-size:11px;color:var(--muted);display:grid;gap:4px}.date-filter button{border:0;border-radius:11px;background:var(--black);color:#fff;padding:11px 18px;font-weight:800;cursor:pointer}
.purchase-row{display:grid;grid-template-columns:1fr auto auto;gap:14px;align-items:center;padding:12px 0;border-bottom:1px solid #eee}.purchase-row:last-child{border:0}.purchase-row span{font-size:12px;color:var(--muted)}
.payment-settings-panel{background:linear-gradient(145deg,#fff,#fffaf0);border-color:#ffe7a3}.payment-settings-grid{display:grid;grid-template-columns:repeat(3,minmax(160px,1fr));gap:12px}.payment-settings-panel .form-field{margin:0}.payment-settings-panel .form-field select,.payment-settings-panel .form-field input{width:100%;border:1px solid #ddd;border-radius:12px;padding:12px;background:#fff;font:inherit}.payment-settings-panel .form-actions{margin-top:12px}.payment-settings-panel .primary{background:#ffc928;color:#111}
.payment-settings-panel.collapsed #paymentSettingsBody,.payment-settings-panel.collapsed .payment-settings-grid,.payment-settings-panel.collapsed .check-field,.payment-settings-panel.collapsed .form-actions{display:none}.driver-referral-editor{margin:12px 0 16px;background:#fff;border:1px solid #ffe2a0;border-radius:16px;padding:14px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end}.driver-referral-editor label{display:grid;gap:6px;font-size:12px;font-weight:800}.driver-referral-editor input{border:1px solid #ddd;border-radius:12px;padding:11px}.driver-referral-editor small{grid-column:1/-1;color:#777}.support-settings-panel{background:#fffdf5;border-color:#ffe7a3}.support-settings-panel .form-actions{margin-top:12px}.support-settings-panel .primary{background:#ffc928;color:#111}
.clickable{cursor:pointer}.clickable:hover{background:#fff8d9}.online{color:var(--green)!important;font-weight:800}
.modal{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:20px}.modal[hidden]{display:none}.modal-backdrop{position:absolute;inset:0;background:#10101099;backdrop-filter:blur(8px)}
.driver-profile{position:relative;width:min(720px,100%);max-height:88vh;overflow:auto;background:#f5f6f8;border-radius:28px;padding:25px;box-shadow:0 30px 90px #0006}.modal-close{position:absolute;right:16px;top:15px;border:0;width:38px;height:38px;border-radius:50%;background:#fff;font-size:24px;cursor:pointer}
.profile-head{display:flex;align-items:center;gap:15px;margin-bottom:18px}.profile-head .avatar{width:62px;height:62px;font-size:23px;border-radius:20px}.profile-head h2{margin:0;font-size:26px}.profile-head p{margin:4px 0;color:var(--muted)}
.profile-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.profile-stat{background:#fff;border-radius:16px;padding:15px}.profile-stat b{display:block;font-size:20px}.profile-stat span{font-size:11px;color:var(--muted)}.orders-title{display:flex;justify-content:space-between;align-items:center}.orders-title select{border:1px solid #ddd;background:#fff;border-radius:12px;padding:9px 12px;font:inherit}.order-card{background:#fff;border-radius:17px;padding:14px;margin-top:9px;border-left:5px solid #bbb}.order-card.completed{border-left-color:#25a65a;background:#f7fff9}.order-card.missed{opacity:.78}.order-card header{margin:0 0 8px}.order-card header>div{display:grid;gap:4px}.order-card p{margin:5px 0;color:#555}.order-status{font-size:10px;font-weight:900;text-transform:uppercase;color:#777}.completed .order-status{color:#16833b}
.route-points{margin:10px 0;padding:9px;background:#f2f3f4;border-radius:12px}.route-points p{display:flex;align-items:flex-start;gap:9px}.route-points p>b{flex:0 0 25px;height:25px;display:grid;place-items:center;border-radius:8px;background:#171717;color:#fff}.route-points span{padding-top:3px}
.contest-studio{display:grid;grid-template-columns:minmax(420px,1.15fr) minmax(300px,.85fr);gap:16px;margin-bottom:25px}.contest-editor{padding:24px;background:linear-gradient(145deg,#fff,#fffaf0);border:0}.contest-editor-head{display:flex;justify-content:space-between;gap:15px;margin-bottom:20px}.contest-editor-head h2,.leaderboard-heading h2{font-size:25px;margin:3px 0}.contest-editor-head p{font-size:12px;color:#777;margin:0}.eyebrow{font-size:9px;letter-spacing:1.7px;font-weight:900;color:#a37400}.save-state{align-self:flex-start;border-radius:20px;background:#e7f7ec;color:#16743b;padding:7px 11px;font-size:10px;font-weight:900}.save-state.saving{background:#fff1c5;color:#8a6200}.save-state.error{background:#ffe0e0;color:#9e2222}.featured-field input{font-size:17px;font-weight:800}.date-pair{display:grid;grid-template-columns:1fr 1fr;gap:10px}.prize-fields{display:grid;gap:8px;margin-top:7px}.prize-input{display:grid;grid-template-columns:105px 1fr;align-items:center;border-radius:15px;padding:10px 12px}.prize-input b{font-size:12px}.prize-input input{border:0;background:#fff9;border-radius:10px;padding:10px;font:inherit;font-weight:800}.prize-input.gold{background:linear-gradient(90deg,#ffe07b,#fff2bd)}.prize-input.silver{background:linear-gradient(90deg,#e2e5ea,#f7f8fa)}.prize-input.bronze{background:linear-gradient(90deg,#e5b28d,#f7dfce)}.contest-actions{display:flex;justify-content:space-between;align-items:center;margin-top:17px}.contest-toggle{display:flex;align-items:center;gap:9px;font-size:12px;font-weight:800}.contest-toggle input{display:none}.contest-toggle i{width:42px;height:24px;background:#bbb;border-radius:20px;position:relative}.contest-toggle i:after{content:'';position:absolute;width:18px;height:18px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}.contest-toggle input:checked+i{background:#1f9d55}.contest-toggle input:checked+i:after{left:21px}.contest-live{background:radial-gradient(circle at 80% 0,#5c4815,#171717 55%);color:#fff;border-radius:25px;padding:25px;box-shadow:0 14px 40px #0002}.live-badge{display:inline-block;background:#ffca28;color:#111;border-radius:20px;padding:6px 10px;font-size:9px;font-weight:1000}.contest-live h3{font-size:27px;margin:18px 0 3px}.contest-live>p{color:#aaa;font-size:12px}.prize-preview{display:grid;gap:8px;margin-top:22px}.preview-prize{display:flex;align-items:center;gap:10px;padding:13px;border:1px solid #ffffff22;border-radius:15px;background:#ffffff0b}.preview-prize:first-child{border-color:#ffc928;background:#ffc92818}.preview-prize strong{font-size:20px}.preview-prize span{margin-left:auto;font-weight:900;color:#ffc928}.leaderboard-heading{display:flex;justify-content:space-between;align-items:end;margin:10px 3px}.leaderboard-heading>span{font-size:11px;color:#777}.leaderboard-table-card{border:0}.muted-note{font-size:11px;color:#777}
.partner-admin-grid{display:grid;grid-template-columns:minmax(320px,520px) 1fr;gap:16px}.form-field{display:grid;gap:6px;font-size:12px;font-weight:700;margin-bottom:12px}.form-field input,.form-field textarea{width:100%;border:1px solid #ddd;border-radius:12px;padding:11px;font:inherit;background:#fafafa}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 10px}.check-field{display:flex;gap:8px;margin:10px 0 16px}.form-actions{display:flex;gap:8px}.admin-ad{display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid #eee}.admin-ad img{width:72px;height:55px;object-fit:cover;border-radius:11px;background:#eee}.admin-ad button{white-space:nowrap}
.form-field:has(#partnerSubtitle),.form-field:has(#partnerDescription),#partnerCount{display:none}.full-ad-preview{height:min(720px,78vh);display:flex;flex-direction:column}.full-ad-preview>img,.full-ad-preview>.preview-image-empty{height:auto;min-height:0;flex:1;object-fit:contain}.phone-ad-footer{display:flex;align-items:center;gap:12px;padding:14px 16px}.phone-ad-footer h2{font-size:19px;margin:0;flex:1}.phone-ad-footer .preview-buttons{margin:0;gap:8px}.phone-ad-footer .preview-buttons button{width:48px;height:48px;font-size:10px}
#partners{position:relative}#partners:before{content:'';position:absolute;inset:-18px -18px auto;height:190px;background:linear-gradient(135deg,#fff2a8,#ffc928);border-radius:28px;z-index:-1}.partner-admin-grid>.panel{border:0;box-shadow:0 16px 45px #8f65001c}.partner-admin-grid>.panel:first-child{background:#fffdf6}.partner-admin-grid .panel-title h2{font-size:21px}.partner-admin-grid .panel-title span{background:#171717;color:#fff;padding:6px 10px;border-radius:20px}.form-field input:focus,.form-field textarea:focus{outline:2px solid #ffc928;border-color:transparent;background:#fff}.form-actions .primary{background:#ffc928;color:#111;flex:1}.admin-ad{background:#f8f8f8;border:0;border-radius:17px;padding:10px;margin-bottom:9px;transition:.2s}.admin-ad:hover{transform:translateY(-2px);box-shadow:0 8px 25px #0001}.admin-ad img{width:82px;height:64px}.admin-ad .grow b{font-size:14px}.inactive-ad{filter:grayscale(.25)}
.ad-preview-modal{position:relative;width:min(430px,100%);max-height:94vh;overflow:auto;background:#f3f3f3;border-radius:28px;padding:18px;box-shadow:0 30px 90px #0006}.preview-heading{display:grid;padding:4px 45px 15px 4px}.preview-heading b{font-size:19px}.preview-heading span{font-size:11px;color:#777}.phone-ad-card{background:#101010;border-radius:27px;overflow:hidden;color:#fff;box-shadow:0 15px 45px #0004}.phone-ad-card>img,.preview-image-empty{display:grid;place-items:center;width:100%;height:245px;object-fit:cover;background:#2b2b2b;color:#999}.phone-ad-body{padding:20px}.phone-ad-body h2{font-size:25px;margin:0}.phone-ad-body h3{font-size:15px;color:#ffc928;margin:5px 0 15px}.preview-points p{display:flex;gap:9px;margin:8px 0}.preview-points b{color:#ffc928}.preview-buttons{display:flex;justify-content:center;gap:17px;margin-top:20px}.preview-buttons button{width:56px;height:56px;border:0;border-radius:50%;color:#fff;font-weight:900;font-size:13px}.preview-buttons .call{background:#ffc928;color:#111;font-size:21px}.preview-buttons .wa{background:#25d366}.preview-buttons .max{background:#2e75ff}
@media(max-width:680px){
  aside .nav span,aside .aside-brand span,aside .aside-bottom span{display:inline!important}.nav{font-size:14px;text-align:left}.aside-brand b{font-size:24px}.aside-bottom button{font-size:12px}.aside-bottom button:after{content:none}
  body{font-size:14px}.login-page{padding:14px}.login-card{padding:25px;border-radius:24px}.login-card h1{font-size:27px}
  main{padding:14px 12px 86px}header{position:sticky;top:0;z-index:50;background:#f4f5f7eF;backdrop-filter:blur(12px);padding:10px 0;margin-bottom:14px}
  .metrics,.metrics.mini{grid-template-columns:1fr 1fr;gap:8px}.metric{padding:13px;border-radius:16px}.metric strong{font-size:22px}.panel{padding:14px;border-radius:18px}
  .date-filter{display:grid;grid-template-columns:1fr 1fr}.date-filter select,.date-filter button{grid-column:1/-1;width:100%}.date-filter input{width:100%}
  .toolbar{display:block}.toolbar input{max-width:none;margin-bottom:8px}.table-panel{padding:0}.table-panel table{min-width:650px}
  .profile-stats{grid-template-columns:1fr 1fr}.driver-profile{padding:20px 14px;border-radius:22px;max-height:94vh}.profile-head{padding-right:35px}.profile-head h2{font-size:21px}
  .purchase-row{grid-template-columns:1fr auto}.purchase-row span{grid-column:1/-1}.withdraw-row{align-items:flex-start;flex-wrap:wrap}.withdraw-row .actions{width:100%}.withdraw-row .actions button{flex:1}
  #driversMap{height:70vh;min-height:420px}.podium{margin-top:10px}.chat-row .danger{font-size:0}.chat-row .danger:after{content:'Г—';font-size:18px}.partner-admin-grid,.contest-studio{grid-template-columns:1fr}.form-grid,.date-pair{grid-template-columns:1fr}.admin-ad{flex-wrap:wrap}.admin-ad .grow{min-width:150px}.contest-editor{padding:17px}.contest-editor-head{display:block}.save-state{display:inline-block;margin-top:9px}.contest-actions{align-items:stretch;gap:10px;flex-direction:column}.prize-input{grid-template-columns:90px 1fr}.leaderboard-heading{display:block}
}
/* Contest scope, newsletter and archive */
.contest-scope{display:grid;grid-template-columns:minmax(220px,.55fr) 1.45fr;gap:18px;padding:18px;border-radius:20px;background:#f7f7f4;margin:16px 0}.tariff-checks{display:flex;flex-wrap:wrap;gap:9px;margin-top:10px}.tariff-checks label{padding:9px 12px;border:1px solid #ddd;border-radius:999px;background:#fff;font-weight:700}.news-history-panel,.contest-history-panel{margin-top:20px}.news-history-row,.contest-history-row{display:flex;align-items:flex-start;gap:18px;padding:17px 0;border-bottom:1px solid #ececec}.news-history-row span,.contest-history-row span,.contest-history-row small{display:block;color:#777;margin-top:4px}.news-history-row p{white-space:pre-wrap;margin:8px 0 0}.history-winners{margin-left:auto;min-width:220px}.history-winners span{color:#222;font-weight:700}.newsletter-card,.news-history-panel{max-width:900px}
@media(max-width:680px){.contest-scope{grid-template-columns:1fr}.news-history-row,.contest-history-row{flex-direction:column}.history-winners{margin-left:0;min-width:0}.news-history-row .danger{width:100%}}
.nav i{display:grid!important;place-items:center;width:36px!important;height:36px!important;border-radius:12px;background:rgba(255,255,255,.08);font-style:normal!important;font-size:18px!important;transition:.2s ease}.nav:hover i{background:rgba(255,201,40,.18);transform:translateY(-1px)}.nav.active i{background:#ffc928!important;color:#111!important;box-shadow:0 7px 18px rgba(255,201,40,.24)}
.category-manager{background:#fff;border:1px solid #f1e4af;border-radius:20px;padding:13px;margin:8px 0 16px;box-shadow:inset 0 0 0 1px #fff8}
.category-manager-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.category-manager-head b{font-size:15px}
.category-row{display:flex;align-items:center;gap:9px;background:#f8f8f8;border-radius:14px;padding:9px;margin-bottom:8px}.category-row .material-symbols-rounded{width:38px;height:38px;border-radius:12px;background:#ffc928;display:grid;place-items:center;color:#111}.category-row small{display:block;color:#777;margin-top:2px}.category-row button{white-space:nowrap}
.admin-ad small{display:block;color:#777;margin-top:3px}.admin-ad .ad-position{width:58px;text-align:center;background:#111;color:#ffc928;border-radius:14px;padding:7px 4px}.admin-ad .ad-position small{color:#fff;font-size:9px}
@media(max-width:680px){.category-row{flex-wrap:wrap}.category-row .grow{min-width:150px}.category-manager .form-actions{flex-direction:column}.category-manager .form-actions button{width:100%}}
.partner-image-list{display:flex;gap:8px;overflow-x:auto;margin:-4px 0 14px;min-height:54px}.partner-image-thumb{width:92px;height:68px;position:relative;flex:0 0 auto;border:1px solid #ddd;border-radius:10px;overflow:hidden;background:#f5f5f5}.partner-image-thumb img{width:100%;height:100%;object-fit:cover}.partner-image-thumb button{position:absolute;right:3px;top:3px;border:0;border-radius:50%;background:#111;color:#fff;width:22px;height:22px}.partner-image-thumb span{position:absolute;left:4px;bottom:4px;background:#111;color:#fff;border-radius:5px;padding:2px 5px;font-size:9px}.partner-image-thumb.local{display:grid;align-content:center;padding:7px;font-size:10px}.preview-photo-strip{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;gap:8px}.preview-photo-strip img{width:100%;min-width:100%;height:260px;object-fit:cover;scroll-snap-align:start;border-radius:18px}
.partners-admin-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.partners-admin-heading h1{font-size:30px;margin:0}.partners-admin-heading p{color:#777;margin:4px 0 0}.partner-add-button{padding:14px 20px!important;border-radius:12px!important;background:#ffc31c!important;color:#111!important}.partner-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:20px}.partner-summary>div{background:#fff;border:1px solid #eee;border-radius:16px;padding:20px;display:grid;gap:5px;box-shadow:0 6px 20px #00000008}.partner-summary b{font-size:28px}.partner-summary span{font-size:12px;color:#777}.partner-summary .active b{color:#1b9b53}.partner-admin-grid{grid-template-columns:1fr}.partner-editor[hidden]{display:none}.partner-editor{max-width:760px;margin:auto}.partner-table-row{display:grid;grid-template-columns:110px minmax(180px,1fr) 150px 160px 90px auto auto;align-items:center;gap:14px;padding:12px;border-bottom:1px solid #eee;background:#fff}.partner-table-row:first-child{border-radius:16px 16px 0 0}.partner-table-row:last-child{border-radius:0 0 16px 16px;border-bottom:0}.partner-table-row img{width:110px;height:72px;object-fit:cover;border-radius:11px;background:#eee}.partner-table-row .grow{display:grid;gap:5px}.partner-table-row .grow b{font-size:16px}.partner-table-row .grow span{font-size:12px;color:#777}.partner-category-pill{background:#fff3cf;color:#7c5700;padding:8px 10px;border-radius:10px;font-size:11px;font-weight:800;text-align:center}.partner-price{font-size:13px}.partner-table-row button{white-space:nowrap}@media(max-width:980px){.partner-table-row{grid-template-columns:90px 1fr auto}.partner-table-row img{width:90px}.partner-category-pill,.partner-price{display:none}.partner-summary{grid-template-columns:1fr}.partners-admin-heading{align-items:flex-start;gap:12px}.partner-add-button{font-size:12px}}
.partner-toolbar{display:grid;grid-template-columns:1fr 220px 190px;gap:12px;background:#fff;border:1px solid #eee;border-radius:16px;padding:16px;margin-bottom:16px}.partner-toolbar input,.partner-toolbar select{border:1px solid #ddd;border-radius:11px;padding:12px;background:#fff;font:inherit}.partner-table-head{display:grid;grid-template-columns:minmax(300px,1fr) 150px 110px 160px 100px;gap:14px;padding:12px 14px;color:#777;background:#f7f7f7;border-radius:12px;font-size:11px;font-weight:800}.partner-table-row{grid-template-columns:110px minmax(180px,1fr) 150px 110px 160px 100px}.partner-status{display:inline-flex;align-items:center;gap:6px;border-radius:10px;padding:8px 10px;font-size:11px;font-weight:800}.partner-status i{width:7px;height:7px;border-radius:50%;background:currentColor}.partner-status.active{background:#e5f7eb;color:#168344}.partner-status.inactive{background:#f0f0f0;color:#777}.partner-row-actions{display:flex;gap:6px}.partner-row-actions button{width:40px;height:40px;padding:0}.partner-editor{position:fixed;z-index:1200;inset:4vh auto auto 50%;transform:translateX(-50%);width:min(720px,calc(100% - 28px));max-height:92vh;overflow:auto;background:#fff!important;border-radius:22px!important;padding:25px!important;box-shadow:0 30px 100px #0007!important}.partner-editor:before{content:'';position:fixed;inset:-10vh -100vw;background:#0008;z-index:-1}.partner-editor-close{position:absolute;right:16px;top:14px;width:38px;height:38px;border:0;border-radius:50%;font-size:24px;background:#f1f1f1;cursor:pointer}.partner-editor .category-manager,.partner-editor .form-field:has(#partnerSubtitle),.partner-editor .form-field:has(#partnerMetro){display:none}.partner-editor .form-field:has(#partnerDescription){display:grid}.partner-editor .panel-title{padding-right:45px}@media(max-width:980px){.partner-toolbar{grid-template-columns:1fr}.partner-table-head{display:none}.partner-table-row{grid-template-columns:80px 1fr auto}.partner-table-row img{width:80px}.partner-table-row .partner-status{grid-column:2}.partner-row-actions{grid-column:3;grid-row:1/3}}
.payment-discount-fold{grid-column:1/-1;border:1px solid #eee;border-radius:18px;background:#fff;padding:12px 14px}.payment-discount-fold summary{display:flex;align-items:center;justify-content:space-between;gap:12px;cursor:pointer;font-weight:900}.payment-discount-fold summary::-webkit-details-marker{display:none}.payment-discount-fold summary span{font-size:12px;color:#777;font-weight:700}.payment-discount-fold summary:after{content:'v';width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:#fff3c4;color:#111}.payment-discount-fold[open] summary:after{content:'v'}.payment-discount-fold .form-field{margin-top:12px}



/* TaxiChi admin polish: stable layout, readable icons, cleaner cards */
html{background:#f4f5f7}body{min-width:320px;overflow-x:hidden}.app{grid-template-columns:248px minmax(0,1fr)}main{width:min(100%,1480px);max-width:1480px;margin:0 auto;padding-left:clamp(18px,2.4vw,34px);padding-right:clamp(18px,2.4vw,34px)}
aside{width:248px}.panel,.metric,.partner-table-row,.purchase-row,.withdraw-row,.driver-profile,.partner-editor{box-shadow:0 10px 28px rgba(0,0,0,.055);border-color:#ececec}.panel{border-radius:24px}.metric{border-radius:22px}.panel-title h2{letter-spacing:-.02em}.panel-title span{line-height:1.35}.toolbar,.date-filter,.partner-toolbar{box-shadow:0 8px 24px rgba(0,0,0,.035)}
.material-symbols-rounded{font-family:'Material Symbols Rounded','Segoe UI Symbol','Arial Unicode MS',sans-serif!important;font-weight:500;font-style:normal;line-height:1;letter-spacing:normal;text-transform:none;white-space:nowrap;word-wrap:normal;direction:ltr;-webkit-font-feature-settings:'liga';-webkit-font-smoothing:antialiased;font-feature-settings:'liga'}
.nav{min-height:48px;border-radius:16px;padding:8px 10px!important;gap:10px!important}.nav i.material-symbols-rounded{flex:0 0 36px;width:36px!important;height:36px!important;font-size:22px!important;overflow:hidden;background:#242424!important;color:#ffc928!important}.nav span{font-size:14px;font-weight:800;letter-spacing:-.01em}.nav.active{box-shadow:0 10px 24px rgba(255,201,40,.24)}.nav.active i.material-symbols-rounded{background:#111!important;color:#ffc928!important}.nav:hover i.material-symbols-rounded{transform:none;background:#333!important;color:#ffc928!important}
button,.primary,.ghost,.danger,.success,.refresh{min-height:40px;border-radius:13px;transition:transform .12s ease,box-shadow .12s ease,background .12s ease}button:hover,.primary:hover,.ghost:hover,.danger:hover,.success:hover,.refresh:hover{transform:translateY(-1px)}input,select,textarea{font-size:14px;line-height:1.35}table{font-size:14px}th{letter-spacing:.04em}.table-panel{border-radius:22px}.table-panel table{min-width:760px}.partner-table-row{border-radius:16px!important;margin-bottom:10px;border-bottom:0}.partner-table-head{margin-bottom:8px}.partner-row-actions button{display:grid;place-items:center;font-size:16px}.payment-settings-panel,.support-settings-panel,.contest-editor{background:#fff!important}.payment-discount-fold summary:after{content:'⌄'}.payment-discount-fold[open] summary:after{content:'⌃'}
@media(max-width:1180px){main{max-width:1180px}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.payment-settings-grid{grid-template-columns:repeat(2,minmax(180px,1fr))}.partner-table-row{grid-template-columns:90px minmax(160px,1fr) 130px 100px 130px 86px}.partner-table-row img{width:90px;height:66px}}
@media(max-width:760px){.app{display:block}main{width:100%;padding:14px 12px 80px}header{gap:10px}.metrics,.metrics.mini{grid-template-columns:1fr}.payment-settings-grid,.partner-toolbar,.date-filter{grid-template-columns:1fr!important}.panel{padding:15px;border-radius:20px}.partner-table-row{grid-template-columns:76px 1fr auto!important;gap:10px}.partner-table-row img{width:76px;height:62px}.partner-row-actions{grid-column:3;grid-row:1/3;flex-direction:column}.partner-row-actions button{width:38px;height:38px}.nav i.material-symbols-rounded{font-size:21px!important}.table-panel{overflow-x:auto}}

.aside-brand{align-items:center;gap:12px;padding:4px 10px 25px!important}.brand-mark{width:46px;height:46px;border-radius:16px;background:#ffc928;display:grid;place-items:center;overflow:hidden;box-shadow:0 10px 28px rgba(255,201,40,.22);flex:0 0 auto}.brand-mark img{width:100%;height:100%;object-fit:cover;display:block}.brand-copy{display:grid;gap:2px;min-width:0}.brand-copy b{font-size:26px!important;line-height:1;color:#ffc928}.brand-copy span{width:max-content;background:#2b2b2b;color:#fff;border-radius:999px;padding:3px 8px;font-size:9px;text-transform:uppercase;letter-spacing:1.5px}.brand-copy small{color:#aaa;font-size:10px;line-height:1.25;max-width:145px}
.partner-editor .form-field:has(#partnerTariff){display:grid}.partner-editor select{width:100%;border:1px solid #ddd;border-radius:12px;padding:11px;background:#fafafa;font:inherit}.partner-editor select:focus{outline:2px solid #ffc928;border-color:transparent;background:#fff}
.partner-image-list{padding:10px;background:#f7f7f7;border:1px dashed #d8d8d8;border-radius:16px}.partner-image-thumb{width:112px!important;height:86px!important;border-radius:16px!important;border:1px solid #e6e6e6!important;box-shadow:0 8px 18px rgba(0,0,0,.06);cursor:grab}.partner-image-thumb:active{cursor:grabbing}.partner-image-thumb.sortable:before{content:'↕';position:absolute;left:6px;top:6px;width:22px;height:22px;border-radius:999px;background:rgba(17,17,17,.72);color:#fff;display:grid;place-items:center;font-size:12px;z-index:2}.partner-image-thumb .thumb-remove{right:6px!important;top:6px!important;width:26px!important;height:26px!important;background:#fff!important;color:#111!important;border:1px solid #e4e4e4!important;box-shadow:0 5px 14px rgba(0,0,0,.16);font-size:18px;line-height:1}.partner-image-thumb .thumb-remove:hover{background:#fee1e1!important;color:#9f1d1d!important}.partner-image-thumb .cover-badge{left:7px!important;bottom:7px!important;border-radius:999px!important;background:#ffc928!important;color:#111!important;font-weight:900}.partner-image-thumb .drag-hint{position:absolute;left:7px;bottom:7px;color:#fff;background:rgba(17,17,17,.68);border-radius:999px;padding:3px 6px;font-size:8px}.partner-image-thumb.local{background:#fffbea!important;border-color:#ffd66b!important;align-content:end!important}.partner-image-thumb.local b{font-size:10px;line-height:1.15}.partner-image-thumb.local em{font-style:normal;color:#8a6500;font-size:9px;font-weight:800}.image-empty-note{padding:12px;color:#777}.primary:disabled{opacity:.7;cursor:wait;transform:none!important}
.partner-table-row .grow small{display:block;color:#777;margin-top:3px;font-size:11px}.partner-table-row .partner-price{font-weight:1000;color:#111}
@media(max-width:1050px){.brand-copy small{display:none}.brand-mark{width:38px;height:38px}.brand-copy b{font-size:21px!important}}

/* Fixed, calm desktop width + real mobile layout */
body{background:#f4f5f7}.app{max-width:1920px;margin:0 auto;grid-template-columns:248px minmax(0,1fr)}main{max-width:1440px}.panel,.partner-toolbar,.date-filter{max-width:100%}img{max-width:100%}
@media(min-width:1600px){main{padding-left:42px;padding-right:42px}.metrics{grid-template-columns:repeat(4,minmax(0,1fr))}.panel{padding:24px}}
@media(max-width:760px){aside{position:fixed;width:270px;transform:translateX(-100%);transition:.22s ease}.app.menu-open aside{transform:none}header{position:sticky;top:0;z-index:60}.aside-brand{padding-bottom:18px!important}.brand-copy small{display:block}.partner-editor{width:calc(100% - 18px)!important;inset:2vh auto auto 50%!important;max-height:96vh!important;padding:18px!important}.partner-image-thumb{width:96px!important;height:76px!important}.partner-table-row .grow span,.partner-table-row .grow small{white-space:normal}.partner-status,.partner-category-pill,.partner-price{font-size:10px}.profile-stats{grid-template-columns:1fr!important}}


.report-row{border-left:4px solid #ffc928}.report-row.new-report{background:#fff8df}.report-row small{display:block;color:#777;margin-top:6px}.provider-wide{grid-column:1/-1}

.subscription-studio{display:grid;gap:18px}
.subscription-hero{display:flex;align-items:center;justify-content:space-between;gap:18px;background:linear-gradient(135deg,#111,#2b2300 48%,#ffc928);color:#fff}
.subscription-hero h2{margin:4px 0 6px;font-size:32px}
.subscription-hero p{margin:0;color:rgba(255,255,255,.78);max-width:720px}
.subscription-hero .eyebrow{color:#ffd64d}
.subscription-hero-actions{display:flex;gap:10px;flex-wrap:wrap}
.subscription-clean-grid{align-items:end}
.provider-box{margin-top:16px;border:1px solid rgba(0,0,0,.08);border-radius:24px;background:#fff;padding:18px;box-shadow:0 10px 28px rgba(0,0,0,.05)}
.provider-box h3{margin:0 0 6px;font-size:20px}
.provider-box p{margin:0 0 14px;color:#667085}
.payment-active-field{margin-top:14px}
.subscription-filter-panel .date-filter{margin:0 0 14px}
@media(max-width:760px){.subscription-hero{display:block}.subscription-hero-actions{margin-top:14px}.subscription-hero h2{font-size:26px}}

