const cfg=window.TAXICHI_CONFIG,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];let DATA=null,MAP=null,MARKERS=[],CURRENT_DRIVER=null;
const titles={overview:'Обзор',users:'Водители',map:'Карта водителей',subscriptions:'Подписки и выплаты',referrals:'Реферальная программа',leaderboard:'ТОП водителей',chat:'Чат водителей',newsletter:'Рассылка',partners:'Реклама и партнёры',system:'Система'};
$('#loginButton').onclick=()=>load($('#token')?.value.trim());$('#refresh').onclick=()=>load(sessionStorage.getItem('taxichi_admin_token'));$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};$('#menu').onclick=()=>$('#app').classList.toggle('menu-open');
all('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));all('.link-page').forEach(b=>b.onclick=()=>page(b.dataset.target));$('#userSearch').oninput=renderUsers;$('#userCity').onchange=renderUsers;$('#subscriptionCity').onchange=()=>renderSubscriptions();
if($('#token'))$('#token').onkeydown=e=>{if(e.key==='Enter')$('#loginButton').click()};
$('#subscriptionPeriod').onchange=()=>{if($('#subscriptionPeriod').value!=='custom'){$('#subscriptionFrom').value='';$('#subscriptionTo').value='';renderSubscriptions()}};
$('#applySubscriptionDates').onclick=()=>renderSubscriptions(true);
$('#partnerSave').onclick=savePartner;$('#partnerReset').onclick=resetPartnerForm;$('#partnerPreview').onclick=previewPartner;
$('#contestSave').onclick=saveContest;
['contestTitle','contestStart','contestEnd','contestPrize1','contestPrize2','contestPrize3','contestActive','contestCity'].forEach(id=>$('#'+id).addEventListener('input',updateContestPreview));all('.contestTariff').forEach(x=>x.addEventListener('change',updateContestPreview));
$('#newsSend').onclick=async()=>{const title=$('#newsTitle').value.trim(),message=$('#newsMessage').value.trim();if(!title||!message)return toast('Заполните заголовок и сообщение');await action({action:'news_send',title,message,city:$('#newsCity').value});$('#newsTitle').value='';$('#newsMessage').value='';await loadNewsHistory()};
document.addEventListener('click',event=>{const driver=event.target.closest('[data-driver]');if(driver)openDriver(driver.dataset.driver);if(event.target.closest('[data-close-driver]'))$('#driverModal').hidden=true;if(event.target.closest('[data-close-preview]'))$('#partnerPreviewModal').hidden=true});
document.addEventListener('change',event=>{if(event.target.id==='driverOrderFilter')renderDriverOrders(event.target.value)});
function page(id){all('.page').forEach(x=>x.classList.toggle('active-page',x.id===id));all('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=titles[id];$('#app').classList.remove('menu-open');if(id==='map')setTimeout(()=>{MAP?.invalidateSize();renderMap()},80);if(id==='newsletter')loadNewsHistory();if(id==='leaderboard')loadContestHistory()}
async function request(method='GET',body){const token=sessionStorage.getItem('taxichi_admin_token')||$('#token')?.value.trim();const response=await fetch(`${cfg.supabaseUrl}/functions/v1/admin-stats`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error(response.status===401?'Неверный логин или пароль':'Ошибка сервера');return response.json()}
async function load(token){if(!token)return $('#loginError').textContent='Введите логин и пароль';try{sessionStorage.setItem('taxichi_admin_token',token);DATA=await request();$('#login').hidden=true;$('#app').hidden=false;$('#updated').textContent=`Обновлено ${new Date(DATA.generated_at).toLocaleTimeString('ru-RU')}`;render()}catch(err){$('#login').hidden=false;$('#app').hidden=true;$('#loginError').textContent=err.message}}
function render(){const d=DATA;renderCityFilters();$('#metrics').innerHTML=[metric('Водителей',d.drivers_total,'Всего аккаунтов','dark'),metric('Онлайн сейчас',d.online,'активность до 2 минут','yellow'),metric('Купили Premium',d.prime_buys,`${d.active_subscriptions} активных`),metric('Выручка',rub(d.revenue_rub),'за всё время'),metric('Активны сегодня',d.active_day,'уникальных'),metric('Активны за неделю',d.active_week,'уникальных'),metric('Активны за месяц',d.active_month,'уникальных'),metric('Заявки на вывод',d.pending_withdrawals,'ожидают обработки')].join('');
$('#activity').innerHTML=[['Сегодня',d.active_day],['7 дней',d.active_week],['30 дней',d.active_month]].map(x=>`<div><b>${num(x[1])}</b><span>${x[0]}</span></div>`).join('');$('#recentMini').innerHTML=(d.recent_users||[]).slice(0,5).map(userRow).join('')||empty('Нет пользователей');$('#topMini').innerHTML=(d.leaderboard||[]).slice(0,5).map((x,i)=>`<div class="mini-row"><div class="avatar">${i+1}</div><div class="grow"><b>${e(x.nickname)}</b><span>${x.completed_orders} заказов</span></div><div class="money">${rub(x.points)}</div></div>`).join('')||empty('Рейтинг пока пуст');renderVersions('#versionMini');renderUsers();renderSubscriptions();renderPaymentSettings();renderReferrals();renderLeaderboard();renderChat();renderPartners();renderSystem();if($('#map').classList.contains('active-page'))renderMap()}
function metric(label,value,note,cls=''){return `<article class="metric ${cls}"><small>${label}</small><strong>${value}</strong><em>${note}</em></article>`}
function userRow(x){const online=(Date.now()-Date.parse(x.last_seen_at||0))<120000;return `<div class="mini-row clickable" data-driver="${e(x.yandex_id)}"><div class="avatar">${initial(x.display_name||x.email)}</div><div class="grow"><b>${e(x.display_name||'Без имени')}</b><span>${e(x.email||x.yandex_id)}</span></div><span class="${online?'online':''}">${ago(x.last_seen_at)}</span></div>`}
function renderCityFilters(){const cities=[...new Set((DATA.recent_users||[]).map(x=>x.last_city).filter(Boolean))].sort();for(const id of ['userCity','subscriptionCity']){const select=$('#'+id),value=select.value;select.innerHTML='<option value="">Все города</option>'+cities.map(c=>`<option value="${e(c)}">${e(cityLabel(c))}</option>`).join('');select.value=value}}
function cityLabel(c){return({'':'Все города',moscow:'Москва',spb:'Санкт-Петербург',ekb:'Екатеринбург',samara:'Самара'})[c]||c}
function renderUsers(){if(!DATA)return;const q=($('#userSearch')?.value||'').toLowerCase(),city=$('#userCity').value;const rows=(DATA.recent_users||[]).filter(x=>`${x.display_name} ${x.email} ${x.yandex_id}`.toLowerCase().includes(q)&&(!city||x.last_city===city));$('#usersCount').textContent=`Показано: ${rows.length}`;$('#usersTable').innerHTML=rows.map(x=>`<tr class="clickable" data-driver="${e(x.yandex_id)}"><td><b>${e(x.display_name||'Без имени')}</b><br><small>${e(x.email||x.yandex_id)}</small></td><td>${e(cityLabel(x.last_city||'—'))}</td><td>${badge(x.subscription)}</td><td>${x.referrals}</td><td>${date(x.created_at)}</td><td>${ago(x.last_seen_at)}</td></tr>`).join('')||`<tr><td colspan="6">Ничего не найдено</td></tr>`}
function renderSubscriptions(custom=false){const d=DATA;if(!d)return;const allPurchases=(d.subscription_purchases||[]).filter(x=>['active','expired'].includes(x.status));let from=null,to=null,label='за всё время';if(custom&&$('#subscriptionFrom').value){from=new Date($('#subscriptionFrom').value+'T00:00:00');to=$('#subscriptionTo').value?new Date($('#subscriptionTo').value+'T23:59:59'):new Date();label=`${from.toLocaleDateString('ru-RU')} — ${to.toLocaleDateString('ru-RU')}`}else{const mode=$('#subscriptionPeriod').value;const start=new Date();start.setHours(0,0,0,0);if(mode==='0'){from=start;label='сегодня'}else if(mode==='1'){to=new Date(start-1);to.setHours(23,59,59,999);from=new Date(start-86400000);label='вчера'}else if(mode!=='all'){from=new Date(start-(Number(mode)-1)*86400000);label=`последние ${mode} дней`}}const purchases=allPurchases.filter(x=>(!from||Date.parse(x.created_at)>=from.getTime())&&(!to||Date.parse(x.created_at)<=to.getTime()));const revenue=purchases.reduce((sum,x)=>sum+Number(x.amount_rub||0),0);$('#subscriptionPeriodLabel').textContent=label;$('#subscriptionMetrics').innerHTML=[metric('Покупок Premium',num(purchases.length),label),metric('Активных подписок',num(d.active_subscriptions),'сейчас'),metric('Выручка',rub(revenue),label)].join('');$('#subscriptionPurchases').innerHTML=purchases.map(x=>`<div class="purchase-row clickable" data-driver="${e(x.yandex_id)}"><div><b>${e(x.yandex_id)}</b><br><span>${date(x.created_at)}</span></div><b>${rub(x.amount_rub)}</b>${badge(x.status)}</div>`).join('')||empty('За выбранный период покупок нет');$('#withdrawals').innerHTML=(d.withdrawals||[]).map(x=>`<div class="withdraw-row"><div class="avatar">₽</div><div class="grow"><b>${rub(x.amount_rub)} · ${e(x.sbp_phone)}</b><span>${date(x.created_at)} · ${e(x.yandex_id)}</span></div>${badge(x.status)}${x.status==='pending'?`<div class="actions"><button class="success" onclick="withdrawal('${x.id}','paid')">Оплачено</button><button class="danger" onclick="withdrawal('${x.id}','rejected')">Отклонить</button></div>`:''}</div>`).join('')||empty('Заявок на вывод нет')}
function renderReferrals(){$('#referralsTable').innerHTML=(DATA.referrals||[]).map((x,i)=>`<tr><td>${i+1}</td><td><b>${e(x.nickname)}</b><br><small>${e(x.yandex_id)}</small></td><td>${x.count}</td><td><span class="badge active">${x.active}</span></td></tr>`).join('')||`<tr><td colspan="4">Рефералов пока нет</td></tr>`}
function renderLeaderboard(){const list=DATA.leaderboard||[],c=DATA.contest||{};$('#contestTitle').value=c.title||'Кубок TaxiChi';$('#contestStart').value=localDateInput(c.starts_at);$('#contestEnd').value=localDateInput(c.ends_at);$('#contestPrize1').value=c.prize_1||'';$('#contestPrize2').value=c.prize_2||'';$('#contestPrize3').value=c.prize_3||'';$('#contestActive').checked=c.active!==false;updateContestPreview();const ordered=[list[1],list[0],list[2]].filter(Boolean);$('#podium').innerHTML=ordered.map(x=>`<div class="podium-card ${x===list[0]?'first':''}"><div class="medal">${x===list[0]?'🥇':x===list[1]?'🥈':'🥉'}</div><b>${e(String(x.nickname||'Водитель').split(' ')[0])}</b><strong>${rub(x.points)}</strong><span>${x.completed_orders} заказов</span></div>`).join('');$('#leaderboardTable').innerHTML=list.map((x,i)=>`<tr><td><b>#${i+1}</b></td><td>${e(String(x.nickname||'Водитель').split(' ')[0])}</td><td><b>${rub(x.points)}</b></td><td>${x.completed_orders}</td><td>${date(x.updated_at)}</td></tr>`).join('')||`<tr><td colspan="5">Рейтинг пока пуст</td></tr>`}
function localDateInput(value){if(!value)return'';const d=new Date(value),offset=d.getTimezoneOffset()*60000;return new Date(d-offset).toISOString().slice(0,16)}
function updateContestPreview(){if(!$('#contestPreviewTitle'))return;if(!$('#contestCity').dataset.ready&&DATA?.contest){$('#contestCity').value=DATA.contest.city||'';const selected=new Set(DATA.contest.tariffs||[]);all('.contestTariff').forEach(x=>x.checked=selected.has(x.value));$('#contestCity').dataset.ready='1'}$('#contestPreviewTitle').textContent=$('#contestTitle').value||'Кубок TaxiChi';const end=$('#contestEnd').value?new Date($('#contestEnd').value):null,tariffs=all('.contestTariff:checked').map(x=>x.parentElement.textContent.trim());$('#contestPreviewDate').textContent=`${cityLabel($('#contestCity').value)} · ${tariffs.join(', ')||'тариф не выбран'} · ${end?'до '+end.toLocaleString('ru-RU'):'укажите финиш'}`;const prizes=[$('#contestPrize1').value,$('#contestPrize2').value,$('#contestPrize3').value];$('#contestPrizePreview').innerHTML=prizes.map((p,i)=>`<div class="preview-prize"><strong>${['🥇','🥈','🥉'][i]}</strong><b>${i+1} место</b><span>${e(p||'Приз не указан')}</span></div>`).join('');$('#contestSaveState').textContent=$('#contestActive').checked?'● Готово к сохранению':'● Конкурс будет выключен';$('#contestSaveState').className='save-state saving'}
async function saveContest(){if(!$('#contestStart').value||!$('#contestEnd').value)return toast('Укажите начало и завершение');const tariffs=all('.contestTariff:checked').map(x=>x.value);if(!tariffs.length)return toast('Выберите хотя бы один тариф');$('#contestSaveState').textContent='● Сохранение…';$('#contestSaveState').className='save-state saving';try{await request('POST',{action:'contest_save',title:$('#contestTitle').value,starts_at:new Date($('#contestStart').value).toISOString(),ends_at:new Date($('#contestEnd').value).toISOString(),city:$('#contestCity').value,tariffs,prize_1:$('#contestPrize1').value,prize_2:$('#contestPrize2').value,prize_3:$('#contestPrize3').value,active:$('#contestActive').checked});$('#contestSaveState').textContent='● Сохранено';$('#contestSaveState').className='save-state';toast('Конкурс обновлён');await load(sessionStorage.getItem('taxichi_admin_token'));page('leaderboard');refreshLiveLeaderboard()}catch(err){$('#contestSaveState').textContent='● Ошибка сохранения';$('#contestSaveState').className='save-state error';toast(err.message)}}
function renderChat(){const list=DATA.chat||[];$('#chatCount').textContent=`${list.length} сообщений`;$('#chatMessages').innerHTML=list.map(x=>`<div class="chat-row"><div class="avatar">${initial(x.sender_name)}</div><div class="message grow"><b>${e(x.sender_name)}</b><span>${e(x.city)} · ${date(x.created_at)}</span>${x.message_text?`<p>${e(x.message_text)}</p>`:''}${x.image_url?`<a href="${safeUrl(x.image_url)}" target="_blank"><img src="${safeUrl(x.image_url)}"></a>`:''}${x.audio_url?`<audio controls src="${safeUrl(x.audio_url)}"></audio>`:''}</div><button class="danger" onclick="deleteMessage('${x.id}')">Удалить</button></div>`).join('')||empty('За последние сутки сообщений нет')}
function renderMap(){if(!window.L||!DATA)return;if(!MAP){MAP=L.map('driversMap').setView([55.75,37.62],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(MAP)}MARKERS.forEach(x=>x.remove());MARKERS=[];const points=DATA.locations||[];$('#mapCount').textContent=points.length;points.forEach(x=>{const m=L.circleMarker([x.latitude,x.longitude],{radius:9,color:'#111',weight:3,fillColor:'#ffc928',fillOpacity:1}).addTo(MAP).bindPopup(`<b>${e(x.name)}</b><br>${e(x.city||'Город не указан')}<br>Точность ±${Math.round(x.accuracy_meters||0)} м<br>${ago(x.updated_at)}`);MARKERS.push(m)});if(points.length){const group=L.featureGroup(MARKERS);MAP.fitBounds(group.getBounds().pad(.25),{maxZoom:13})}}
function renderSystem(){const d=DATA;$('#systemMetrics').innerHTML=[metric('Установок',num(d.installs),'устройств'),metric('Ошибка прогноза',`${d.prediction_error_percent||0}%`,'средняя за 30 дней'),metric('Сервер','Онлайн','данные обновляются')].join('');renderVersions('#versions')}
function renderVersions(target){const allVersions=(DATA.versions||[]).filter(x=>/^\d+(\.\d+)+$/.test(x.version));const latest=allVersions.sort((a,b)=>b.version.localeCompare(a.version,undefined,{numeric:true}))[0];const list=latest?[latest]:[];$(target).innerHTML=list.map(x=>`<div class="bar-row"><b>${e(x.version)} · актуальная</b><div class="bar"><i style="width:100%"></i></div><span>${x.count}</span></div>`).join('')||empty('Нет данных об актуальной версии')}
async function withdrawal(id,status){if(!confirm(status==='paid'?'Подтвердить, что деньги выплачены?':'Отклонить вывод и вернуть сумму на баланс?'))return;await action({action:'withdrawal',id,status})}async function deleteMessage(id){if(confirm('Удалить сообщение у всех водителей?'))await action({action:'delete_message',id})}async function action(body){try{await request('POST',body);toast('Готово');await load(sessionStorage.getItem('taxichi_admin_token'))}catch(err){toast(err.message)}}
function openDriver(id){const user=(DATA.recent_users||[]).find(x=>x.yandex_id===id);if(!user)return;CURRENT_DRIVER=id;const orders=(DATA.order_history||[]).filter(x=>x.yandex_id===id);const score=(DATA.leaderboard||[]).find(x=>x.yandex_id===id);const earned=orders.filter(isCompletedOrder).reduce((sum,x)=>sum+Number(x.actual_price||0),0);$('#driverProfileContent').innerHTML=`<div class="profile-head"><div class="avatar">${initial(user.display_name||user.email)}</div><div><h2>${e(user.display_name||'Водитель')}</h2><p>${e(user.email||user.yandex_id)}</p><span class="${ago(user.last_seen_at)==='Онлайн'?'online':''}">${ago(user.last_seen_at)}</span></div></div><div class="profile-stats"><div class="profile-stat"><b>${badge(user.subscription)}</b><span>Подписка</span></div><div class="profile-stat"><b>${num(user.referrals)}</b><span>Рефералов</span></div><div class="profile-stat"><b>${rub(score?.points||earned)}</b><span>Заработок за месяц</span></div></div><div class="orders-title"><h3>Заказы</h3><select id="driverOrderFilter"><option value="all">Все</option><option value="completed">Завершённые</option><option value="missed">Не взятые</option></select></div><div id="driverOrders"></div>`;renderDriverOrders('all');$('#driverModal').hidden=false}
function renderPartners(){const list=DATA.partner_ads||[];$('#partnerCount').textContent=`${list.length}/10`;$('#partnerCards').innerHTML=list.map(x=>`<div class="admin-ad ${x.active?'':'inactive-ad'}"><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e(x.subtitle||'')} · место ${Number(x.sort_order)+1}</span></div><label class="ad-switch"><input type="checkbox" ${x.active?'checked':''} onchange="togglePartner('${x.id}',this.checked)"><i></i><span>${x.active?'Активна':'Неактивна'}</span></label><button class="ghost" onclick="editPartner('${x.id}')">?зменить</button><button class="ghost" onclick="copyPartner('${x.id}')">Копировать</button><button class="danger" onclick="deletePartner('${x.id}')">Удалить</button></div>`).join('')||empty('Карточек пока нет')}
function editPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;$('#partnerId').value=x.id;$('#partnerTitle').value=x.title||'';$('#partnerSubtitle').value=x.subtitle||'';$('#partnerDescription').value=x.description||'';$('#partnerImageUrl').value=x.image_url||'';$('#partnerPhone').value=x.phone_url||'';$('#partnerWhatsapp').value=x.whatsapp_url||'';$('#partnerMax').value=x.max_url||'';$('#partnerOrder').value=Number(x.sort_order||0)+1;$('#partnerActive').checked=x.active!==false;scrollTo({top:0,behavior:'smooth'})}
async function copyPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;await action({action:'partner_save',title:x.title,subtitle:x.subtitle,description:x.description,image_url:x.image_url,phone_url:x.phone_url,whatsapp_url:x.whatsapp_url,max_url:x.max_url,sort_order:Math.min(9,(DATA.partner_ads||[]).length),active:false});toast('Неактивный шаблон создан')}
async function togglePartner(id,active){await action({action:'partner_toggle',id,active})}
async function previewPartner(){let image=$('#partnerImageUrl').value.trim(),file=$('#partnerImage').files[0];if(file)image=URL.createObjectURL(file);const title=$('#partnerTitle').value.trim()||'Название партнёра';$('#partnerPreviewCarousel').innerHTML=`<div class="phone-ad-card full-ad-preview">${image?`<img src="${e(image)}">`:`<div class="preview-image-empty">Ваше рекламное изображение</div>`}<div class="phone-ad-footer"><h2>${e(title)}</h2><div class="preview-buttons">${$('#partnerPhone').value?'<button class="call">?</button>':''}${$('#partnerWhatsapp').value?'<button class="wa">WA</button>':''}${$('#partnerMax').value?'<button class="max">MAX</button>':''}</div></div></div>`;$('#partnerPreviewModal').hidden=false}
function resetPartnerForm(){['partnerId','partnerTitle','partnerSubtitle','partnerDescription','partnerImageUrl','partnerPhone','partnerWhatsapp','partnerMax'].forEach(id=>$('#'+id).value='');$('#partnerImage').value='';$('#partnerOrder').value=1;$('#partnerActive').checked=true}
async function savePartner(){try{let image=$('#partnerImageUrl').value.trim(),file=$('#partnerImage').files[0];if(file){if(file.size>5*1024*1024)throw new Error('Фото должно быть меньше 5 МБ');const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const uploaded=await request('POST',{action:'partner_upload',image_base64:base64});image=uploaded.url}await action({action:'partner_save',id:$('#partnerId').value,title:$('#partnerTitle').value,subtitle:$('#partnerSubtitle').value,description:$('#partnerDescription').value,image_url:image,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked});resetPartnerForm()}catch(err){toast(err.message)}}
async function deletePartner(id){if(confirm('Удалить рекламную карточку?'))await action({action:'partner_delete',id})}
function isCompletedOrder(x){return Number(x.actual_price||0)>0||Boolean(x.completed_at)}
function renderDriverOrders(mode='all'){if(!CURRENT_DRIVER)return;let orders=(DATA.order_history||[]).filter(x=>x.yandex_id===CURRENT_DRIVER);if(mode==='completed')orders=orders.filter(isCompletedOrder);if(mode==='missed')orders=orders.filter(x=>!isCompletedOrder(x));$('#driverOrders').innerHTML=orders.slice(0,100).map(x=>{const done=isCompletedOrder(x);return `<div class="order-card ${done?'completed':'missed'}"><header><div><span class="order-status">${done?'✓ Завершён':'Не взят'}</span><b>${e(x.tariff||'Тариф')}</b></div><strong>${rub(done?x.actual_price:x.predicted_price)}</strong></header><div class="route-points"><p><b>А</b><span>${e(x.pickup_address||'Адрес не сохранён')}</span></p></div><p>Маршрут: ${Number(x.distance_km||0).toLocaleString('ru-RU')} км · ${num(x.duration_minutes)} мин</p><p>Коэффициент ×${Number(x.coefficient||1).toLocaleString('ru-RU')} · ${date(x.completed_at||x.created_at)}</p></div>`}).join('')||empty('В этой категории заказов нет')}
function badge(status){const map={active:'Активна',expired:'?стекла',pending:'Ожидает',paid:'Оплачено',rejected:'Отклонено',none:'Нет'};return `<span class="badge ${status}">${map[status]||e(status)}</span>`}function rub(v){return `${num(v)} ₽`}function num(v){return Number(v||0).toLocaleString('ru-RU')}function date(v){return v?new Date(v).toLocaleString('ru-RU'):'—'}function ago(v){if(!v)return'—';const sec=Math.max(0,(Date.now()-new Date(v))/1000);return sec<120?'Онлайн':sec<3600?`${Math.floor(sec/60)} мин назад`:sec<86400?`${Math.floor(sec/3600)} ч назад`:date(v)}function initial(v){return e(String(v||'?').trim()[0]?.toUpperCase()||'?')}function empty(t){return `<p style="color:#888;text-align:center;padding:20px">${e(t)}</p>`}function e(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}function safeUrl(v){try{const u=new URL(v);return u.protocol==='https:'?e(u.href):''}catch{return''}}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
async function loadNewsHistory(){if(!$('#newsHistory'))return;$('#newsHistory').innerHTML=empty('Загрузка…');try{const data=await request('POST',{action:'news_list'}),items=data.items||[];$('#newsHistory').innerHTML=items.map(x=>`<div class="news-history-row"><div class="grow"><b>${e(x.title)}</b><span>${e(cityLabel(x.city||'Все города'))} · ${date(x.created_at)}</span><p>${e(x.message)}</p></div><button class="danger" onclick="deleteNews('${x.id}')">Удалить</button></div>`).join('')||empty('Рассылок пока нет')}catch(err){$('#newsHistory').innerHTML=empty(err.message)}}
async function deleteNews(id){if(confirm('Удалить эту новость из приложения?')){await action({action:'news_delete',id});await loadNewsHistory()}}
function renderPartners(){const list=DATA.partner_ads||[];$('#partnerCount').textContent=`${list.length} карточек`;$('#partnerCards').innerHTML=list.map(x=>`<div class="admin-ad ${x.active?'':'inactive-ad'}"><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e(cityLabel(x.city||'Все города'))} · ${e(x.subtitle||'')} · место ${Number(x.sort_order)+1}</span></div><label class="ad-switch"><input type="checkbox" ${x.active?'checked':''} onchange="togglePartner('${x.id}',this.checked)"><i></i><span>${x.active?'Активна':'Неактивна'}</span></label><button class="ghost" onclick="editPartner('${x.id}')">?зменить</button><button class="ghost" onclick="copyPartner('${x.id}')">Копировать</button><button class="danger" onclick="deletePartner('${x.id}')">Удалить</button></div>`).join('')||empty('Карточек пока нет')}
function editPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;$('#partnerId').value=x.id;$('#partnerCity').value=x.city||'';$('#partnerTitle').value=x.title||'';$('#partnerSubtitle').value=x.subtitle||'';$('#partnerDescription').value=x.description||'';$('#partnerImageUrl').value=x.image_url||'';$('#partnerPhone').value=x.phone_url||'';$('#partnerWhatsapp').value=x.whatsapp_url||'';$('#partnerMax').value=x.max_url||'';$('#partnerOrder').value=Number(x.sort_order||0)+1;$('#partnerActive').checked=x.active!==false;scrollTo({top:0,behavior:'smooth'})}
async function copyPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;await action({action:'partner_save',title:x.title,city:x.city||'',subtitle:x.subtitle,description:x.description,image_url:x.image_url,phone_url:x.phone_url,whatsapp_url:x.whatsapp_url,max_url:x.max_url,sort_order:Math.min(9,(DATA.partner_ads||[]).length),active:false});toast('Неактивный шаблон создан')}
function resetPartnerForm(){['partnerId','partnerTitle','partnerSubtitle','partnerDescription','partnerImageUrl','partnerPhone','partnerWhatsapp','partnerMax'].forEach(id=>$('#'+id).value='');$('#partnerCity').value='';$('#partnerImage').value='';$('#partnerOrder').value=1;$('#partnerActive').checked=true}
async function savePartner(){try{let image=$('#partnerImageUrl').value.trim(),file=$('#partnerImage').files[0];if(file){if(file.size>5*1024*1024)throw new Error('Фото должно быть меньше 5 МБ');const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const uploaded=await request('POST',{action:'partner_upload',image_base64:base64});image=uploaded.url}await action({action:'partner_save',id:$('#partnerId').value,city:$('#partnerCity').value,title:$('#partnerTitle').value,subtitle:$('#partnerSubtitle').value,description:$('#partnerDescription').value,image_url:image,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked});resetPartnerForm()}catch(err){toast(err.message)}}
async function loadContestHistory(){if(!$('#contestHistory'))return;$('#contestHistory').innerHTML=empty('Загрузка…');try{const data=await request('POST',{action:'contest_history'}),items=data.items||[];$('#contestHistory').innerHTML=items.map(x=>`<div class="contest-history-row"><div><b>${e(x.title)}</b><span>${e(cityLabel(x.city||'Все города'))} · ${date(x.starts_at)} — ${date(x.ends_at)}</span><small>${(x.tariffs||[]).map(e).join(', ')}</small></div><div class="history-winners">${(x.winners||[]).map((w,i)=>`<span>${i+1}. ${e(w.nickname)} — ${rub(w.points)}</span>`).join('')||'<span>Результатов нет</span>'}</div></div>`).join('')||empty('Завершённых конкурсов пока нет')}catch(err){$('#contestHistory').innerHTML=empty(err.message)}}
function renderPartners(){const list=DATA.partner_ads||[];$('#partnerCount').textContent=`${list.length} карточек`;$('#partnerCards').innerHTML=list.map(x=>`<div class="admin-ad ${x.active?'':'inactive-ad'}"><div class="ad-position"><b>${Number(x.sort_order)+1}</b><small>${e(cityLabel(x.city||'Все города'))}</small></div><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e(x.subtitle||'')}</span></div><label class="ad-switch"><input type="checkbox" ${x.active?'checked':''} onchange="togglePartner('${x.id}',this.checked)"><i></i><span>${x.active?'Активна':'Неактивна'}</span></label><button class="ghost" onclick="editPartner('${x.id}')">?зменить</button><button class="ghost" onclick="copyPartner('${x.id}')">Копировать</button><button class="danger" onclick="deletePartner('${x.id}')">Удалить</button></div>`).join('')||empty('Карточек пока нет')}
async function loadContestHistory(){if(!$('#contestHistory'))return;$('#contestHistory').innerHTML=empty('Загрузка…');try{const data=await request('POST',{action:'contest_history'}),items=data.items||[];$('#contestHistory').innerHTML=items.map(x=>`<div class="contest-history-row"><div class="grow"><b>${e(x.title)}</b><span>${e(cityLabel(x.city||'Все города'))} · ${date(x.starts_at)} — ${date(x.ends_at)}</span><small>${(x.tariffs||[]).map(e).join(', ')}</small><div class="history-winners">${(x.winners||[]).map((w,i)=>`<span>${i+1}. ${e(w.nickname)} — ${rub(w.points)}</span>`).join('')||'<span>Результатов нет</span>'}</div></div><button class="danger" onclick="deleteContestHistory('${x.id}')">Удалить</button></div>`).join('')||empty('Завершённых конкурсов пока нет')}catch(err){$('#contestHistory').innerHTML=empty(err.message)}}
async function deleteContestHistory(id){if(confirm('Удалить этот конкурс из истории?')){await action({action:'contest_history_delete',id});await loadContestHistory()}}
function openDriver(id){const user=(DATA.recent_users||[]).find(x=>x.yandex_id===id);if(!user)return;CURRENT_DRIVER=id;const orders=(DATA.order_history||[]).filter(x=>x.yandex_id===id),score=(DATA.leaderboard||[]).find(x=>x.yandex_id===id),earned=orders.filter(isCompletedOrder).reduce((sum,x)=>sum+Number(x.actual_price||0),0);$('#driverProfileContent').innerHTML=`<div class="profile-head"><div class="avatar">${initial(user.display_name||user.email)}</div><div><h2>${e(user.display_name||'Водитель')}</h2><p>${e(user.email||user.yandex_id)}</p><span class="${ago(user.last_seen_at)==='Онлайн'?'online':''}">${ago(user.last_seen_at)}</span></div></div><div class="profile-access"><button class="success" onclick="grantDriverAccess('${e(id)}')">Открыть подписку</button><button class="danger" onclick="revokeDriverAccess('${e(id)}')">Закрыть подписку</button></div><div class="profile-stats"><div class="profile-stat"><b>${badge(user.subscription)}</b><span>Подписка</span></div><div class="profile-stat"><b>${num(user.referrals)}</b><span>Рефералов</span></div><div class="profile-stat"><b>${rub(score?.points||earned)}</b><span>Заработок за месяц</span></div></div><div class="orders-title"><h3>Заказы</h3><select id="driverOrderFilter"><option value="all">Все</option><option value="completed">Завершённые</option><option value="missed">Не взятые</option></select></div><div id="driverOrders"></div>`;renderDriverOrders('all');$('#driverModal').hidden=false}
async function grantDriverAccess(id){if(confirm('Открыть этому водителю полный бесплатный доступ?')){await action({action:'grant_access',yandex_id:id});$('#driverModal').hidden=true}}
async function revokeDriverAccess(id){if(confirm('Закрыть бесплатный служебный доступ?')){await action({action:'revoke_access',yandex_id:id});$('#driverModal').hidden=true}}
function renderLiveLeaderboard(list){const ordered=[list[1],list[0],list[2]].filter(Boolean);$('#podium').innerHTML=ordered.map(x=>`<div class="podium-card ${x===list[0]?'first':''}"><div class="medal">${x===list[0]?'🥇':x===list[1]?'🥈':'🥉'}</div><b>${e(String(x.nickname||'Водитель').split(' ')[0])}</b><strong>${rub(x.points)}</strong><span>${x.completed_orders} заказов</span></div>`).join('');$('#leaderboardTable').innerHTML=list.map((x,i)=>`<tr><td><b>#${i+1}</b></td><td>${e(String(x.nickname||'Водитель').split(' ')[0])}</td><td><b>${rub(x.points)}</b></td><td>${x.completed_orders}</td><td>${date(x.updated_at)}</td></tr>`).join('')||`<tr><td colspan="5">Рейтинг пока пуст</td></tr>`}
async function refreshLiveLeaderboard(){if(!$('#leaderboard').classList.contains('active-page')||!sessionStorage.getItem('taxichi_admin_token'))return;try{const result=await request('POST',{action:'contest_live'});DATA.leaderboard=result.items||[];renderLiveLeaderboard(DATA.leaderboard);$('#updated').textContent=`Рейтинг онлайн · ${new Date(result.updated_at).toLocaleTimeString('ru-RU')}`}catch(_){}}
const saved=sessionStorage.getItem('taxichi_admin_token');if(saved)load(saved);setInterval(()=>{if(saved||sessionStorage.getItem('taxichi_admin_token'))load(sessionStorage.getItem('taxichi_admin_token'))},30000);setInterval(refreshLiveLeaderboard,5000);

function partnerCategoryTitle(id){const c=(DATA?.partner_categories||[]).find(x=>x.id===id);return c?.title||'Без раздела'}
function renderPartnerCategoryControls(){const cats=DATA?.partner_categories||[];const select=$('#partnerCategory');if(select){select.innerHTML='<option value="">Выберите категорию</option>'+cats.map(c=>`<option value="${e(c.id)}">${e(c.title)}</option>`).join('')}
  const filter=$('#partnerCategoryFilter');if(filter){const current=filter.value;filter.innerHTML='<option value="">Все категории</option>'+cats.map(c=>`<option value="${e(c.id)}">${e(c.title)}</option>`).join('');filter.value=current}
  const list=$('#categoryList');if(list){list.innerHTML=cats.map(c=>`<div class="category-row ${c.active?'':'inactive-ad'}"><span class="material-symbols-rounded">${e(c.icon||'local_offer')}</span><div class="grow"><b>${e(c.title)}</b><small>${e(c.slug||'')} · порядок ${Number(c.sort_order||0)+1}</small></div><label class="ad-switch"><input type="checkbox" ${c.active?'checked':''} onchange="togglePartnerCategory('${c.id}',this.checked)"><i></i><span>${c.active?'Активен':'Скрыт'}</span></label><button class="ghost" onclick="editPartnerCategory('${c.id}')">?зменить</button><button class="danger" onclick="deletePartnerCategory('${c.id}')">Удалить</button></div>`).join('')||empty('Разделов пока нет')}}
function renderPartners(){renderPartnerCategoryControls();const list=DATA.partner_ads||[];$('#partnerCount').textContent=`${list.length} объявлений`;$('#partnerCards').innerHTML=list.map(x=>`<div class="admin-ad ${x.active?'':'inactive-ad'}"><div class="ad-position"><b>${Number(x.sort_order||0)+1}</b><small>${e(cityLabel(x.city||'Все города'))}</small></div><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e(partnerCategoryTitle(x.category_id))} · ? ${Number(x.rating||0).toLocaleString('ru-RU')} (${Number(x.reviews_count||0)})</span><small>${e(x.address||x.subtitle||'')}</small></div><label class="ad-switch"><input type="checkbox" ${x.active?'checked':''} onchange="togglePartner('${x.id}',this.checked)"><i></i><span>${x.active?'Активна':'Неактивна'}</span></label><button class="ghost" onclick="editPartner('${x.id}')">?зменить</button><button class="ghost" onclick="copyPartner('${x.id}')">Копировать</button><button class="danger" onclick="deletePartner('${x.id}')">Удалить</button></div>`).join('')||empty('Объявлений пока нет')}
function editPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;$('#partnerId').value=x.id;$('#partnerCategory').value=x.category_id||'';$('#partnerCity').value=x.city||'';$('#partnerTitle').value=x.title||'';$('#partnerSubtitle').value=x.subtitle||'';$('#partnerDescription').value=x.description||'';$('#partnerAddress').value=x.address||'';$('#partnerMetro').value=x.metro||'';$('#partnerHours').value=x.work_hours||'';$('#partnerImageUrl').value=x.image_url||'';$('#partnerPhone').value=x.phone_url||'';$('#partnerWhatsapp').value=x.whatsapp_url||'';$('#partnerMax').value=x.max_url||'';$('#partnerOrder').value=Number(x.sort_order||0)+1;$('#partnerActive').checked=x.active!==false;scrollTo({top:0,behavior:'smooth'})}
function resetPartnerForm(){['partnerId','partnerTitle','partnerSubtitle','partnerDescription','partnerAddress','partnerMetro','partnerHours','partnerImageUrl','partnerPhone','partnerWhatsapp','partnerMax'].forEach(id=>{const el=$('#'+id);if(el)el.value=''});if($('#partnerCategory'))$('#partnerCategory').value='';$('#partnerCity').value='';$('#partnerImage').value='';$('#partnerOrder').value=1;$('#partnerActive').checked=true}
async function copyPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;await action({action:'partner_save',title:x.title,city:x.city||'',category_id:x.category_id||'',subtitle:x.subtitle,description:x.description,address:x.address||'',metro:x.metro||'',work_hours:x.work_hours||'',price_label:x.price_label||'',image_url:x.image_url,image_urls:partnerImages(x),phone_url:x.phone_url,whatsapp_url:x.whatsapp_url,max_url:x.max_url,sort_order:(DATA.partner_ads||[]).length,active:false});toast('Неактивный шаблон создан')}
async function savePartner(){try{let image=$('#partnerImageUrl').value.trim(),file=$('#partnerImage').files[0];if(file){if(file.size>5*1024*1024)throw new Error('Фото должно быть меньше 5 МБ');const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const uploaded=await request('POST',{action:'partner_upload',image_base64:base64});image=uploaded.url}await action({action:'partner_save',id:$('#partnerId').value,city:$('#partnerCity').value,category_id:$('#partnerCategory').value,title:$('#partnerTitle').value,subtitle:$('#partnerSubtitle').value,description:$('#partnerDescription').value,address:$('#partnerAddress').value,metro:$('#partnerMetro').value,work_hours:$('#partnerHours').value,image_url:image,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked});resetPartnerForm()}catch(err){toast(err.message)}}
async function previewPartner(){let image=$('#partnerImageUrl').value.trim(),file=$('#partnerImage').files[0];if(file)image=URL.createObjectURL(file);const title=$('#partnerTitle').value.trim()||'Название партнёра',rating='? '+(($('#partnerId').value&&(DATA.partner_ads||[]).find(x=>x.id===$('#partnerId').value)?.rating)||'—');$('#partnerPreviewCarousel').innerHTML=`<div class="phone-ad-card full-ad-preview">${image?`<img src="${e(image)}">`:`<div class="preview-image-empty">Фото объявления</div>`}<div class="phone-ad-body"><h2>${e(title)}</h2><h3>${e(partnerCategoryTitle($('#partnerCategory').value))} · ${rating}</h3><div class="preview-points">${($('#partnerDescription').value||'Описание объявления').split('\n').filter(Boolean).slice(0,5).map(x=>`<p><b>✓</b>${e(x)}</p>`).join('')}</div></div><div class="phone-ad-footer"><div class="preview-buttons">${$('#partnerPhone').value?'<button class="call">?</button>':''}${$('#partnerWhatsapp').value?'<button class="wa">WA</button>':''}${$('#partnerMax').value?'<button class="max">MAX</button>':''}</div></div></div>`;$('#partnerPreviewModal').hidden=false}
function editPartnerCategory(id){const x=(DATA.partner_categories||[]).find(v=>v.id===id);if(!x)return;$('#categoryId').value=x.id;$('#categoryTitle').value=x.title||'';$('#categoryIcon').value=x.icon||'local_offer';$('#categoryOrder').value=Number(x.sort_order||0)+1;$('#categoryActive').checked=x.active!==false}
function resetPartnerCategory(){['categoryId','categoryTitle'].forEach(id=>$('#'+id).value='');$('#categoryIcon').value='local_offer';$('#categoryOrder').value=(DATA?.partner_categories||[]).length+1;$('#categoryActive').checked=true}
async function savePartnerCategory(){try{await action({action:'partner_category_save',id:$('#categoryId').value,title:$('#categoryTitle').value,icon:$('#categoryIcon').value,sort_order:Math.max(0,Number($('#categoryOrder').value||1)-1),active:$('#categoryActive').checked});resetPartnerCategory()}catch(err){toast(err.message)}}
async function deletePartnerCategory(id){if(confirm('Удалить раздел? Объявления останутся, но будут без раздела.'))await action({action:'partner_category_delete',id})}
async function togglePartnerCategory(id,active){await action({action:'partner_category_toggle',id,active})}
let PARTNER_IMAGES=[],PARTNER_FILES=[];
function partnerImages(x){const values=Array.isArray(x?.image_urls)?x.image_urls:[];return [...new Set([...values,x?.image_url].filter(Boolean))].slice(0,8)}
function enteredPartnerUrls(){return $('#partnerImageUrl').value.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean)}
function renderPartnerImages(){const remote=[...new Set([...PARTNER_IMAGES,...enteredPartnerUrls()])].slice(0,8),local=PARTNER_FILES.slice(0,Math.max(0,8-remote.length));$('#partnerImageList').innerHTML=[...remote.map((url,i)=>`<div class="partner-image-thumb"><img src="${safeUrl(url)}"><button type="button" onclick="removePartnerImage(${i})">×</button>${i===0?'<span>Обложка</span>':''}</div>`),...local.map((file,i)=>`<div class="partner-image-thumb local"><button type="button" onclick="removePartnerFile(${i})">×</button><b>${e(file.name)}</b><small>${Math.ceil(file.size/1024)} КБ</small></div>`)].join('')||'<small>Фотографии пока не выбраны</small>'}
function removePartnerImage(index){PARTNER_IMAGES.splice(index,1);$('#partnerImageUrl').value=PARTNER_IMAGES.join('\n');renderPartnerImages()}
function removePartnerFile(index){PARTNER_FILES.splice(index,1);renderPartnerImages()}
function appendPartnerFiles(){PARTNER_FILES=[...PARTNER_FILES,...($('#partnerImage').files||[])].slice(0,8);$('#partnerImage').value='';renderPartnerImages()}
async function uploadPartnerFile(file){if(file.size>5*1024*1024)throw new Error(`Фото ${file.name} больше 5 МБ`);const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});return (await request('POST',{action:'partner_upload',image_base64:base64})).url}
function openPartnerEditor(mode='partner'){const editor=$('#partnerEditor');editor.classList.toggle('category-mode',mode==='category');const title=editor.querySelector('.panel-title h2'),note=editor.querySelector('.panel-title span');if(title)title.textContent=mode==='category'?'Категории партнёров':'Объявление партнёра';if(note)note.textContent=mode==='category'?'можно добавить или изменить разделы':'обязательны только категория и название';editor.hidden=false;editor.scrollIntoView({behavior:'smooth',block:'start'})}
function editPartner(id){const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(!x)return;openPartnerEditor();$('#partnerId').value=x.id;$('#partnerCategory').value=x.category_id||'';$('#partnerCity').value=x.city||'';$('#partnerTitle').value=x.title||'';$('#partnerSubtitle').value=x.subtitle||'';$('#partnerDescription').value=x.description||'';$('#partnerAddress').value=x.address||'';$('#partnerMetro').value=x.metro||'';$('#partnerHours').value=x.work_hours||'';$('#partnerPrice').value=x.price_label||'';PARTNER_IMAGES=partnerImages(x);$('#partnerImageUrl').value=PARTNER_IMAGES.join('\n');$('#partnerPhone').value=x.phone_url||'';$('#partnerWhatsapp').value=x.whatsapp_url||'';$('#partnerMax').value=x.max_url||'';$('#partnerOrder').value=Number(x.sort_order||0)+1;$('#partnerActive').checked=x.active!==false;renderPartnerImages()}
function resetPartnerForm(){['partnerId','partnerTitle','partnerSubtitle','partnerDescription','partnerAddress','partnerMetro','partnerHours','partnerPrice','partnerImageUrl','partnerPhone','partnerWhatsapp','partnerMax'].forEach(id=>$('#'+id).value='');PARTNER_IMAGES=[];PARTNER_FILES=[];$('#partnerCategory').value='';$('#partnerCity').value='';$('#partnerImage').value='';$('#partnerOrder').value=1;$('#partnerActive').checked=true;renderPartnerImages()}
async function savePartner(){try{const category=$('#partnerCategory').value,title=$('#partnerTitle').value.trim(),address=$('#partnerAddress').value.trim(),hours=$('#partnerHours').value.trim(),description=$('#partnerDescription').value.trim();if(!category)throw new Error('Выберите категорию объявления');if(!title||!address||!hours||!description)throw new Error('Заполните название, адрес, график работы и описание');const uploaded=[];for(const file of [...$('#partnerImage').files].slice(0,8))uploaded.push(await uploadPartnerFile(file));const image_urls=[...new Set([...PARTNER_IMAGES,...enteredPartnerUrls(),...uploaded])].slice(0,8);await action({action:'partner_save',id:$('#partnerId').value,city:$('#partnerCity').value,category_id:category,title,subtitle:$('#partnerSubtitle').value,description,address,metro:$('#partnerMetro').value,work_hours:hours,price_label:$('#partnerPrice').value,image_url:image_urls[0]||'',image_urls,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked});resetPartnerForm();$('#partnerEditor').hidden=true}catch(err){toast(err.message)}}
function previewPartner(){const urls=[...PARTNER_IMAGES,...enteredPartnerUrls()],slides=[...urls.map(safeUrl),...PARTNER_FILES.map(URL.createObjectURL)].slice(0,8),phone=$('#partnerPhone').value,wa=$('#partnerWhatsapp').value,max=$('#partnerMax').value,price=$('#partnerPrice').value.trim()||'Цена не указана',description=$('#partnerDescription').value.trim()||'Описание не заполнено';$('#partnerPreviewCarousel').innerHTML=`<div class="admin-preview-gallery">${slides.length?slides.map((x,i)=>`<figure><img src="${x}" alt="Фото ${i+1}">${i===0?'<small>Обложка</small>':''}</figure>`).join(''):'<div class="preview-image-empty">Добавьте фотографии</div>'}</div><div class="admin-preview-content"><div class="admin-preview-category">${e(partnerCategoryTitle($('#partnerCategory').value))}</div><div class="admin-preview-title"><h2>${e($('#partnerTitle').value.trim()||'Название партнёра')}</h2><strong>${e(price)}</strong></div><div class="admin-preview-meta"><p><b>📍 Адрес</b><span>${e($('#partnerAddress').value||'Не указан')}</span></p><p><b>🕘 График работы</b><span>${e($('#partnerHours').value||'Не указан')}</span></p></div><section><b>Описание</b><p>${e(description).replace(/\n/g,'<br>')}</p></section><div class="admin-preview-map"><span>📍</span><div><b>Расположение партнёра</b><small>${e($('#partnerAddress').value||'Адрес появится здесь')}</small></div></div><div class="admin-preview-contacts">${phone?'<button class="call">☎ Позвонить</button>':''}${wa?'<button class="wa">WhatsApp</button>':''}${max?'<button class="max">MAX</button>':''}${!phone&&!wa&&!max?'<small>Контакты пока не добавлены</small>':''}</div></div>`;$('#partnerPreviewModal').hidden=false}
function renderPartners(){renderPartnerCategoryControls();const all=DATA.partner_ads||[],search=($('#partnerSearch')?.value||'').trim().toLowerCase(),category=$('#partnerCategoryFilter')?.value||'',status=$('#partnerStatusFilter')?.value||'';const list=all.filter(x=>(!search||`${x.title} ${x.subtitle||''} ${x.description||''} ${x.address||''}`.toLowerCase().includes(search))&&(!category||x.category_id===category)&&(!status||(status==='active'?x.active:!x.active)));$('#partnerTotal').textContent=all.length;$('#partnerActiveCount').textContent=all.filter(x=>x.active).length;$('#partnerInactiveCount').textContent=all.filter(x=>!x.active).length;$('#partnerCount').textContent=`${list.length} партнёров`;$('#partnerCards').innerHTML=list.map(x=>`<div class="partner-table-row ${x.active?'':'inactive-ad'}"><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e(x.subtitle||x.description||x.address||'Описание не указано')}</span></div><span class="partner-category-pill">${e(partnerCategoryTitle(x.category_id))}</span><label class="partner-status ${x.active?'active':'inactive'}"><i></i>${x.active?'Активный':'Неактивный'}</label><b class="partner-price">${e(x.price_label||'Цена не указана')}</b><div class="partner-row-actions"><button class="ghost" onclick="editPartner('${x.id}')">✎</button><button class="danger" onclick="deletePartner('${x.id}')">⋮</button></div></div>`).join('')||empty('Партнёры не найдены')}
if($('#partnerAdd'))$('#partnerAdd').onclick=()=>{resetPartnerForm();openPartnerEditor('partner')};if($('#partnerCategories'))$('#partnerCategories').onclick=()=>{renderPartnerCategoryControls();openPartnerEditor('category')};if($('#partnerEditorClose'))$('#partnerEditorClose').onclick=()=>{$('#partnerEditor').hidden=true;$('#partnerEditor').classList.remove('category-mode')};['partnerSearch','partnerCategoryFilter','partnerStatusFilter'].forEach(id=>{if($('#'+id))$('#'+id).oninput=renderPartners});if($('#partnerImage'))$('#partnerImage').onchange=appendPartnerFiles;if($('#partnerImageUrl'))$('#partnerImageUrl').oninput=renderPartnerImages;
function currentPartnerPayload(image_urls){return {action:'partner_save',id:$('#partnerId').value,city:$('#partnerCity').value,category_id:$('#partnerCategory').value,title:$('#partnerTitle').value.trim(),subtitle:$('#partnerSubtitle').value,description:$('#partnerDescription').value.trim(),address:$('#partnerAddress').value.trim(),metro:$('#partnerMetro').value,work_hours:$('#partnerHours').value.trim(),price_label:$('#partnerPrice').value.trim(),image_url:image_urls[0]||'',image_urls,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked}}
async function savePartnerOptional(){try{const category=$('#partnerCategory').value,title=$('#partnerTitle').value.trim(),price=$('#partnerPrice').value.trim();if(!category)throw new Error('Выберите категорию объявления');if(!title)throw new Error('Укажите название партнёра');const uploaded=[];for(const file of PARTNER_FILES.slice(0,8))uploaded.push(await uploadPartnerFile(file));const image_urls=[...new Set([...PARTNER_IMAGES,...enteredPartnerUrls(),...uploaded])].slice(0,8),payload=currentPartnerPayload(image_urls),saved=await request('POST',payload);if(saved.item){const list=DATA.partner_ads||[],i=list.findIndex(x=>x.id===saved.item.id);if(i>=0)list[i]=saved.item;else list.unshift(saved.item);renderPartners()}toast('Сохранено');await load(sessionStorage.getItem('taxichi_admin_token'));const savedRow=saved.item||(DATA.partner_ads||[]).find(x=>payload.id?x.id===payload.id:x.title===payload.title&&x.category_id===payload.category_id);if(price&&savedRow&&String(savedRow.price_label||'')!==price){toast('Цена не сохранилась: обновите серверную функцию и миграцию price_label');return}resetPartnerForm();$('#partnerEditor').hidden=true}catch(err){toast(err.message)}}
savePartner=savePartnerOptional;window.savePartner=savePartnerOptional;
if($('#partnerSave')){$('#partnerSave').onclick=savePartnerOptional}if($('#partnerReset'))$('#partnerReset').onclick=resetPartnerForm;if($('#partnerPreview'))$('#partnerPreview').onclick=previewPartner;if($('#categorySave'))$('#categorySave').onclick=savePartnerCategory;if($('#categoryReset'))$('#categoryReset').onclick=resetPartnerCategory;if($('#categoryNew'))$('#categoryNew').onclick=resetPartnerCategory;renderPartnerImages();

function paymentSettings(){return DATA?.payment_settings||{provider:'manual',provider_title:'СБП / ручная оплата',monthly_price_rub:499,discount_percent:20,referral_percent:10,payout_mode:'manual',active:true}}
function renderPaymentSettings(){if(!$('#paymentPrice'))return;const p=paymentSettings();$('#paymentProvider').value=['manual','yookassa','robokassa'].includes(p.provider)?p.provider:'manual';$('#paymentProviderTitle').value=p.provider_title||'СБП / ручная оплата';$('#paymentPrice').value=p.monthly_price_rub||499;$('#paymentDiscount').value=p.discount_percent??20;$('#paymentReferralPercent').value=p.referral_percent??10;$('#paymentPayoutMode').value=p.payout_mode||'manual';$('#paymentActive').checked=p.active!==false;const final=Math.max(1,Math.round(Number(p.monthly_price_rub||499)*(100-Number(p.discount_percent||0))/100));$('#paymentSettingsState').textContent=`${p.provider_title||'Провайдер'} · ${p.monthly_price_rub||499} ₽, со скидкой ${final} ₽ · рефералу ${p.referral_percent??10}%`}
async function savePaymentSettings(){try{const payload={action:'payment_settings_save',provider:$('#paymentProvider').value,provider_title:$('#paymentProviderTitle').value.trim(),monthly_price_rub:Number($('#paymentPrice').value||499),discount_percent:Number($('#paymentDiscount').value||0),referral_percent:Number($('#paymentReferralPercent').value||10),payout_mode:$('#paymentPayoutMode').value,active:$('#paymentActive').checked};const result=await request('POST',payload);DATA.payment_settings=result.item||payload;renderPaymentSettings();toast('Настройки оплаты сохранены');await load(sessionStorage.getItem('taxichi_admin_token'))}catch(err){toast(err.message)}}
if($('#paymentSettingsSave'))$('#paymentSettingsSave').onclick=savePaymentSettings;

function enhancePaymentSettingsPanel(){
  const panel=document.querySelector('.payment-settings-panel');if(!panel||$('#paymentProviderApiUrl'))return;
  const title=panel.querySelector('.panel-title');if(title&&!$('#paymentSettingsToggle')){const btn=document.createElement('button');btn.id='paymentSettingsToggle';btn.className='ghost';btn.type='button';btn.textContent='Свернуть';title.insertBefore(btn,title.children[1]||null);btn.onclick=()=>{panel.classList.toggle('collapsed');btn.textContent=panel.classList.contains('collapsed')?'Развернуть':'Свернуть'};}
  const grid=panel.querySelector('.payment-settings-grid');if(grid)grid.insertAdjacentHTML('beforeend',`
    <label class="form-field">API URL провайдера<input id="paymentProviderApiUrl" placeholder="https://api.provider.ru/..."></label>
    <label class="form-field">Ссылка оплаты / checkout<input id="paymentProviderPaymentUrl" placeholder="https://pay.provider.ru/..."></label>
    <label class="form-field">Кабинет провайдера<input id="paymentProviderDashboardUrl" placeholder="https://dashboard.provider.ru/..."></label>
    <label class="form-field">Документация / помощь<input id="paymentProviderHelpUrl" placeholder="https://docs.provider.ru/..."></label>`);
  const discountLabel=$('#paymentDiscount')?.closest('label');if(grid&&discountLabel&&!$('#paymentDiscountFold')){const fold=document.createElement('details');fold.id='paymentDiscountFold';fold.className='payment-discount-fold';fold.open=false;fold.innerHTML='<summary><b>Скидка</b><span>Процент скидки для Premium</span></summary>';grid.insertBefore(fold,discountLabel);fold.appendChild(discountLabel);}
}
const baseRenderPaymentSettings=renderPaymentSettings;
renderPaymentSettings=function(){enhancePaymentSettingsPanel();baseRenderPaymentSettings();const p=paymentSettings();if($('#paymentProviderApiUrl')){$('#paymentProviderApiUrl').value=p.provider_api_url||'';$('#paymentProviderPaymentUrl').value=p.provider_payment_url||'';$('#paymentProviderDashboardUrl').value=p.provider_dashboard_url||'';$('#paymentProviderHelpUrl').value=p.provider_help_url||'';}}
savePaymentSettings=async function(){try{const payload={action:'payment_settings_save',provider:$('#paymentProvider').value,provider_title:$('#paymentProviderTitle').value.trim(),monthly_price_rub:Number($('#paymentPrice').value||499),discount_percent:Number($('#paymentDiscount').value||0),referral_percent:Number($('#paymentReferralPercent').value||10),payout_mode:$('#paymentPayoutMode').value,provider_api_url:$('#paymentProviderApiUrl')?.value||'',provider_payment_url:$('#paymentProviderPaymentUrl')?.value||'',provider_dashboard_url:$('#paymentProviderDashboardUrl')?.value||'',provider_help_url:$('#paymentProviderHelpUrl')?.value||'',active:$('#paymentActive').checked};const result=await request('POST',payload);DATA.payment_settings=result.item||payload;renderPaymentSettings();toast('Настройки оплаты сохранены');await load(sessionStorage.getItem('taxichi_admin_token'))}catch(err){toast(err.message)}}
if($('#paymentSettingsSave'))$('#paymentSettingsSave').onclick=savePaymentSettings;

const baseOpenDriver=openDriver;
openDriver=function(id){baseOpenDriver(id);const user=(DATA.recent_users||[]).find(x=>x.yandex_id===id);if(!user||!$('#driverProfileContent'))return;const global=paymentSettings().referral_percent??10;const value=user.referral_percent_override??'';const box=document.createElement('div');box.className='driver-referral-editor';box.innerHTML=`<label>?ндивидуальный % рефералки<input id="driverReferralPercent" inputmode="numeric" placeholder="${global}" value="${e(value)}"></label><button class="ghost" id="driverReferralSave">Сохранить процент</button><small>Пусто = общий процент из настроек оплаты (${global}%). После сохранения водитель увидит этот процент в приложении.</small>`;const anchor=$('#driverProfileContent .profile-access')||$('#driverProfileContent .profile-stats');anchor?.after(box);$('#driverReferralSave').onclick=async()=>{try{await request('POST',{action:'driver_referral_percent_save',yandex_id:id,referral_percent:$('#driverReferralPercent').value});toast('Процент рефералки обновлён');await load(sessionStorage.getItem('taxichi_admin_token'));openDriver(id)}catch(err){toast(err.message)}}}

function supportSettings(){return DATA?.support_settings||{title:'Поддержка TaxiChi',description:'Если нужна помощь, напишите нам удобным способом.',email:'',whatsapp_url:'',telegram_url:'',max_url:''}}
function ensureSupportPanel(){const page=$('#system');if(!page||$('#supportSettingsSave'))return;page.insertAdjacentHTML('afterbegin',`<article class="panel support-settings-panel"><div class="panel-title"><h2>Поддержка в приложении</h2><span>почта и ссылки меняются без новой сборки</span></div><div class="payment-settings-grid"><label class="form-field">Заголовок<input id="supportTitle"></label><label class="form-field">Email<input id="supportEmail" placeholder="support@example.ru"></label><label class="form-field">WhatsApp<input id="supportWhatsapp" placeholder="https://wa.me/..."></label><label class="form-field">Telegram<input id="supportTelegram" placeholder="https://t.me/..."></label><label class="form-field">MAX<input id="supportMax" placeholder="https://max.ru/..."></label><label class="form-field">Описание<input id="supportDescription"></label></div><div class="form-actions"><button id="supportSettingsSave" class="primary">Сохранить поддержку</button></div></article>`);$('#supportSettingsSave').onclick=saveSupportSettings}
function renderSupportSettings(){ensureSupportPanel();const s=supportSettings();if(!$('#supportTitle'))return;$('#supportTitle').value=s.title||'';$('#supportDescription').value=s.description||'';$('#supportEmail').value=s.email||'';$('#supportWhatsapp').value=s.whatsapp_url||'';$('#supportTelegram').value=s.telegram_url||'';$('#supportMax').value=s.max_url||''}
async function saveSupportSettings(){try{const result=await request('POST',{action:'support_settings_save',title:$('#supportTitle').value,description:$('#supportDescription').value,email:$('#supportEmail').value,whatsapp_url:$('#supportWhatsapp').value,telegram_url:$('#supportTelegram').value,max_url:$('#supportMax').value});DATA.support_settings=result.item;renderSupportSettings();toast('Поддержка сохранена')}catch(err){toast(err.message)}}
const baseRenderSystem=renderSystem;renderSystem=function(){baseRenderSystem();renderSupportSettings();}

const partnerTariffLabels={economy:'Эконом',comfort:'Комфорт',comfort_plus:'Комфорт+',business:'Бизнес',premier:'Премьер',elite:'Элит',cruise:'Круиз',minivan:'Минивэн',delivery:'Доставка'};
let PARTNER_IMAGE_DRAG=null,PARTNER_FILE_DRAG=null;
function partnerTariffLabel(value){return partnerTariffLabels[value]||value||''}
function partnerAdDate(value){if(!value)return 'Дата не указана';const d=new Date(value);return Number.isNaN(d.getTime())?'Дата не указана':d.toLocaleDateString('ru-RU')}
function syncPartnerImagesInput(){if($('#partnerImageUrl'))$('#partnerImageUrl').value=PARTNER_IMAGES.join('\n')}
function dragPartnerImage(index){PARTNER_IMAGE_DRAG=index}
function dropPartnerImage(index){if(PARTNER_IMAGE_DRAG===null||PARTNER_IMAGE_DRAG===index)return;const item=PARTNER_IMAGES.splice(PARTNER_IMAGE_DRAG,1)[0];PARTNER_IMAGES.splice(index,0,item);PARTNER_IMAGE_DRAG=null;syncPartnerImagesInput();renderPartnerImages()}
function dragPartnerFile(index){PARTNER_FILE_DRAG=index}
function dropPartnerFile(index){if(PARTNER_FILE_DRAG===null||PARTNER_FILE_DRAG===index)return;const item=PARTNER_FILES.splice(PARTNER_FILE_DRAG,1)[0];PARTNER_FILES.splice(index,0,item);PARTNER_FILE_DRAG=null;renderPartnerImages()}
renderPartnerImages=function(){const remote=[...new Set([...PARTNER_IMAGES,...enteredPartnerUrls()])].slice(0,8);PARTNER_IMAGES=remote;syncPartnerImagesInput();const local=PARTNER_FILES.slice(0,Math.max(0,8-remote.length));$('#partnerImageList').innerHTML=[...remote.map((url,i)=>`<div class="partner-image-thumb sortable" draggable="true" ondragstart="dragPartnerImage(${i})" ondragover="event.preventDefault()" ondrop="dropPartnerImage(${i})"><img src="${safeUrl(url)}"><button class="thumb-remove" type="button" onclick="removePartnerImage(${i})" aria-label="Удалить фото">×</button>${i===0?'<span class="cover-badge">Обложка</span>':'<small class="drag-hint">перетащите</small>'}</div>`),...local.map((file,i)=>`<div class="partner-image-thumb local sortable" draggable="true" ondragstart="dragPartnerFile(${i})" ondragover="event.preventDefault()" ondrop="dropPartnerFile(${i})"><button class="thumb-remove" type="button" onclick="removePartnerFile(${i})" aria-label="Удалить фото">×</button><b>${e(file.name)}</b><small>${Math.ceil(file.size/1024)} КБ</small><em>${remote.length+i===0?'Обложка':'будет загружено'}</em></div>`)].join('')||'<small class="image-empty-note">Фотографии пока не выбраны. Первое фото станет обложкой.</small>'}
const baseEditPartnerFinal=editPartner;
editPartner=function(id){baseEditPartnerFinal(id);const x=(DATA.partner_ads||[]).find(v=>v.id===id);if(x&&$('#partnerTariff'))$('#partnerTariff').value=x.tariff||'';renderPartnerImages()}
const baseResetPartnerFormFinal=resetPartnerForm;
resetPartnerForm=function(){baseResetPartnerFormFinal();if($('#partnerTariff'))$('#partnerTariff').value='';renderPartnerImages()}
function currentPartnerPayload(image_urls){return {action:'partner_save',id:$('#partnerId').value,city:$('#partnerCity').value,category_id:$('#partnerCategory').value,tariff:$('#partnerTariff')?.value||'',title:$('#partnerTitle').value.trim(),subtitle:$('#partnerSubtitle').value,description:$('#partnerDescription').value.trim(),address:$('#partnerAddress').value.trim(),metro:$('#partnerMetro').value,work_hours:$('#partnerHours').value.trim(),price_label:$('#partnerPrice').value.trim(),image_url:image_urls[0]||'',image_urls,phone_url:$('#partnerPhone').value,whatsapp_url:$('#partnerWhatsapp').value,max_url:$('#partnerMax').value,sort_order:Math.max(0,Number($('#partnerOrder').value||1)-1),active:$('#partnerActive').checked}}
savePartnerOptional=async function(){const btn=$('#partnerSave'),old=btn?.textContent;try{const category=$('#partnerCategory').value,title=$('#partnerTitle').value.trim(),price=$('#partnerPrice').value.trim();if(!category)throw new Error('Выберите категорию объявления');if(!title)throw new Error('Укажите название партнёра');if(btn){btn.disabled=true;btn.textContent=PARTNER_FILES.length?'Загрузка фото…':'Сохранение…'}const uploaded=[];for(const file of PARTNER_FILES.slice(0,8)){uploaded.push(await uploadPartnerFile(file));if(btn)btn.textContent=`Загружено ${uploaded.length}/${PARTNER_FILES.length}`;}const image_urls=[...new Set([...PARTNER_IMAGES,...enteredPartnerUrls(),...uploaded])].slice(0,8),payload=currentPartnerPayload(image_urls);if(btn)btn.textContent='Сохранение карточки…';const saved=await request('POST',payload);if(saved.item){const list=DATA.partner_ads||[],i=list.findIndex(x=>x.id===saved.item.id);if(i>=0)list[i]=saved.item;else list.unshift(saved.item);renderPartners()}toast('Сохранено');await load(sessionStorage.getItem('taxichi_admin_token'));const savedRow=saved.item||(DATA.partner_ads||[]).find(x=>payload.id?x.id===payload.id:x.title===payload.title&&x.category_id===payload.category_id);if(price&&savedRow&&String(savedRow.price_label||'')!==price){toast('Цена не сохранилась: обновите серверную функцию и миграцию price_label');return}resetPartnerForm();$('#partnerEditor').hidden=true}catch(err){toast(err.message)}finally{if(btn){btn.disabled=false;btn.textContent=old||'Сохранить карточку'}}}
savePartner=savePartnerOptional;window.savePartner=savePartnerOptional;if($('#partnerSave'))$('#partnerSave').onclick=savePartnerOptional;if($('#partnerReset'))$('#partnerReset').onclick=resetPartnerForm;
previewPartner=function(){const urls=[...PARTNER_IMAGES,...enteredPartnerUrls()],slides=[...urls.map(safeUrl),...PARTNER_FILES.map(URL.createObjectURL)].slice(0,8),phone=$('#partnerPhone').value,wa=$('#partnerWhatsapp').value,max=$('#partnerMax').value,price=$('#partnerPrice').value.trim()||'Цена не указана',description=$('#partnerDescription').value.trim()||'Описание не заполнено',tariff=partnerTariffLabel($('#partnerTariff')?.value||'');$('#partnerPreviewCarousel').innerHTML=`<div class="admin-preview-gallery">${slides.length?slides.map((x,i)=>`<figure><img src="${x}" alt="Фото ${i+1}">${i===0?'<small>Обложка</small>':''}</figure>`).join(''):'<div class="preview-image-empty">Добавьте фотографии</div>'}</div><div class="admin-preview-content"><div class="admin-preview-category">${e(partnerCategoryTitle($('#partnerCategory').value))}${tariff?` · ${e(tariff)}`:''}</div><div class="admin-preview-title"><h2>${e($('#partnerTitle').value.trim()||'Название партнёра')}</h2><strong>${e(price)}</strong></div><div class="admin-preview-meta"><p><b>📍 Адрес</b><span>${e($('#partnerAddress').value||'Не указан')}</span></p><p><b>🕘 График работы</b><span>${e($('#partnerHours').value||'Не указан')}</span></p></div><section><b>Описание</b><p>${e(description).replace(/\n/g,'<br>')}</p></section><div class="admin-preview-map"><span>📍</span><div><b>Расположение партнёра</b><small>${e($('#partnerAddress').value||'Адрес появится здесь')}</small></div></div><div class="admin-preview-contacts">${phone?'<button class="call">☎ Позвонить</button>':''}${wa?'<button class="wa">WhatsApp</button>':''}${max?'<button class="max">MAX</button>':''}${!phone&&!wa&&!max?'<small>Контакты пока не добавлены</small>':''}</div></div>`;$('#partnerPreviewModal').hidden=false}
if($('#partnerPreview'))$('#partnerPreview').onclick=previewPartner;
renderPartners=function(){renderPartnerCategoryControls();const all=DATA.partner_ads||[],search=($('#partnerSearch')?.value||'').trim().toLowerCase(),category=$('#partnerCategoryFilter')?.value||'',status=$('#partnerStatusFilter')?.value||'';const list=all.filter(x=>(!search||`${x.title} ${x.subtitle||''} ${x.description||''} ${x.address||''} ${x.tariff||''}`.toLowerCase().includes(search))&&(!category||x.category_id===category)&&(!status||(status==='active'?x.active:!x.active)));$('#partnerTotal').textContent=all.length;$('#partnerActiveCount').textContent=all.filter(x=>x.active).length;$('#partnerInactiveCount').textContent=all.filter(x=>!x.active).length;$('#partnerCount').textContent=`${list.length} партнёров`;$('#partnerCards').innerHTML=list.map(x=>`<div class="partner-table-row ${x.active?'':'inactive-ad'}"><img src="${safeUrl(x.image_url)}"><div class="grow"><b>${e(x.title)}</b><span>${e([partnerTariffLabel(x.tariff),x.address||x.description||'Описание не указано'].filter(Boolean).join(' · '))}</span><small>★ ${Number(x.rating||4.8).toFixed(1)} · ${partnerAdDate(x.created_at)}</small></div><span class="partner-category-pill">${e(partnerCategoryTitle(x.category_id))}</span><label class="partner-status ${x.active?'active':'inactive'}"><i></i>${x.active?'Активный':'Неактивный'}</label><b class="partner-price">${e(x.price_label||'Цена не указана')}</b><div class="partner-row-actions"><button class="ghost" onclick="editPartner('${x.id}')">✎</button><button class="danger" onclick="deletePartner('${x.id}')">⋮</button></div></div>`).join('')||empty('Партнёры не найдены')}
renderPartnerImages();


function renderChatReports(){
  if(!$('#chatReports'))return;
  const list=DATA?.chat_reports||[];
  $('#chatReportsCount').textContent=`${list.filter(x=>x.status==='new').length} \u043d\u043e\u0432\u044b\u0445 \u00b7 ${list.length} \u0432\u0441\u0435\u0433\u043e`;
  $('#chatReports').innerHTML=list.map(x=>`<div class="chat-row report-row ${x.status==='new'?'new-report':''}"><div class="avatar">!</div><div class="message grow"><b>${e(x.reported_sender_name||'\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')}</b><span>${e(cityLabel(x.city||''))} \u00b7 ${date(x.created_at)} \u00b7 \u0436\u0430\u043b\u043e\u0431\u0430: ${e(x.reason||'\u0416\u0430\u043b\u043e\u0431\u0430')}</span>${x.message_text?`<p>${e(x.message_text)}</p>`:''}${x.image_url?`<a href="${safeUrl(x.image_url)}" target="_blank"><img src="${safeUrl(x.image_url)}"></a>`:''}${x.audio_url?`<audio controls src="${safeUrl(x.audio_url)}"></audio>`:''}<small>\u041f\u043e\u0436\u0430\u043b\u043e\u0432\u0430\u043b\u0441\u044f: ${e(x.reporter_name||x.reporter_id||'\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')}</small></div><div class="actions"><button class="success" onclick="reviewReport('${x.id}','reviewed')">\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e</button><button class="ghost" onclick="blockChatUser('${e(x.reported_sender_id||'')}','${e(x.city||'')}','mute')">Мут 24ч</button><button class="danger" onclick="deleteMessage('${x.message_id}')">\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u043c\u0441</button><button class="danger" onclick="blockChatUser('${e(x.reported_sender_id||'')}','${e(x.city||'')}','ban')">Бан</button></div></div>`).join('')||empty('\u0416\u0430\u043b\u043e\u0431 \u043f\u043e\u043a\u0430 \u043d\u0435\u0442');
}
async function reviewReport(id,status){await action({action:'report_review',id,status})}
async function blockChatUser(yandexId,city,type){if(!yandexId)return toast('Нет ID водителя');const label=type==='ban'?'забанить':'поставить мут';if(!confirm(`Точно ${label} этого водителя в чате?`))return;await action({action:'chat_block',yandex_id:yandexId,city,block_type:type,hours:type==='ban'?24*365:24,reason:type==='ban'?'Блокировка по жалобе':'Мут по жалобе'})}
if(typeof renderChat==='function'&&!window.__taxichiReportsHook){window.__taxichiReportsHook=true;const oldRenderChat=renderChat;renderChat=function(){oldRenderChat();renderChatReports();}}

function ensureProviderFields(){
  const grid=document.querySelector('.payment-settings-grid');if(!grid||$('#paymentSbpEnabled'))return;
  ['paymentProviderApiUrl','paymentProviderPaymentUrl','paymentProviderDashboardUrl','paymentProviderHelpUrl'].forEach(id=>{$('#'+id)?.closest('label')?.classList.add('provider-generic')});
  grid.insertAdjacentHTML('beforeend',`
    <label class="check-field provider-wide"><input id="paymentFullAccessForAll" type="checkbox" checked> Полный доступ всем без оплаты</label>
    <label class="check-field provider-wide provider-manual"><input id="paymentSbpEnabled" type="checkbox" checked> \u0421\u0411\u041f \u0432\u043a\u043b\u044e\u0447\u0451\u043d</label>
    <label class="form-field provider-yookassa">YooKassa shopId<input id="yookassaShopId" placeholder="shopId from YooKassa dashboard"></label>
    <label class="form-field provider-yookassa">YooKassa secret key<input id="yookassaSecretKey" type="password" placeholder="API secret key"></label>
    <label class="form-field provider-yookassa">YooKassa return_url<input id="yookassaReturnUrl" placeholder="https://helper.taxichi.pro/pay/success"></label>
    <label class="form-field provider-yookassa">YooKassa webhook URL<input id="yookassaWebhookUrl" placeholder="https://.../functions/v1/payment-webhook"></label>
    <label class="form-field provider-robokassa">Robokassa MerchantLogin<input id="robokassaMerchantLogin" placeholder="MerchantLogin"></label>
    <label class="form-field provider-robokassa">Robokassa Password #1<input id="robokassaPassword1" type="password"></label>
    <label class="form-field provider-robokassa">Robokassa Password #2<input id="robokassaPassword2" type="password"></label>
    <label class="form-field provider-robokassa">Robokassa ResultURL<input id="robokassaResultUrl" placeholder="https://.../functions/v1/payment-webhook"></label>
    <label class="form-field provider-robokassa">Robokassa SuccessURL<input id="robokassaSuccessUrl" placeholder="https://helper.taxichi.pro/pay/success"></label>
    <label class="form-field provider-robokassa">Robokassa FailURL<input id="robokassaFailUrl" placeholder="https://helper.taxichi.pro/pay/fail"></label>
    <label class="check-field provider-robokassa"><input id="robokassaIsTest" type="checkbox" checked> Robokassa test mode</label>
  `);
  $('#paymentProvider').onchange=()=>{renderProviderVisibility()};
}
function renderProviderVisibility(){
  ['paymentProviderApiUrl','paymentProviderPaymentUrl','paymentProviderDashboardUrl','paymentProviderHelpUrl'].forEach(id=>{const label=$('#'+id)?.closest('label');if(label){label.classList.add('provider-legacy-generic');label.hidden=true;}});
  const provider=$('#paymentProvider')?.value||'manual';
  const showYoo=provider==='yookassa',showRobo=provider==='robokassa',showManual=provider==='manual';
  all('.provider-yookassa').forEach(x=>x.hidden=!showYoo);
  all('.provider-robokassa').forEach(x=>x.hidden=!showRobo);
  all('.provider-manual').forEach(x=>x.hidden=!showManual);
  all('.provider-generic,.provider-legacy-generic').forEach(x=>x.hidden=true);
  const help={manual:'\u0421\u0411\u041f / \u0440\u0443\u0447\u043d\u0430\u044f \u043e\u043f\u043b\u0430\u0442\u0430: \u0432\u043a\u043b\u044e\u0447\u0438\u0442\u0435 \u0421\u0411\u041f \u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u0435.',yookassa:'YooKassa: fill shopId, secret key, return_url and webhook URL.',robokassa:'Robokassa: fill MerchantLogin, Password #1/#2 and Result/Success/Fail URLs.'};
  const state=$('#paymentSettingsState');if(state&&help[provider])state.textContent=help[provider];
}
if(typeof renderPaymentSettings==='function'&&!window.__taxichiProviderHook){
  window.__taxichiProviderHook=true;
  const oldRenderPaymentSettings=renderPaymentSettings;
  renderPaymentSettings=function(){ensureProviderFields();oldRenderPaymentSettings();const p=paymentSettings();
    if($('#paymentSbpEnabled')){$('#paymentFullAccessForAll').checked=p.full_access_for_all!==false;$('#paymentSbpEnabled').checked=p.sbp_enabled!==false;$('#yookassaShopId').value=p.yookassa_shop_id||'';$('#yookassaSecretKey').value=p.yookassa_secret_key||'';$('#yookassaReturnUrl').value=p.yookassa_return_url||'';$('#yookassaWebhookUrl').value=p.yookassa_webhook_url||'';$('#robokassaMerchantLogin').value=p.robokassa_merchant_login||'';$('#robokassaPassword1').value=p.robokassa_password1||'';$('#robokassaPassword2').value=p.robokassa_password2||'';$('#robokassaResultUrl').value=p.robokassa_result_url||'';$('#robokassaSuccessUrl').value=p.robokassa_success_url||'';$('#robokassaFailUrl').value=p.robokassa_fail_url||'';$('#robokassaIsTest').checked=p.robokassa_is_test!==false;renderProviderVisibility();}
  };
  savePaymentSettings=async function(){try{const payload={action:'payment_settings_save',provider:$('#paymentProvider').value,provider_title:$('#paymentProviderTitle').value.trim(),monthly_price_rub:Number($('#paymentPrice').value||499),discount_percent:Number($('#paymentDiscount').value||0),referral_percent:Number($('#paymentReferralPercent').value||10),payout_mode:$('#paymentPayoutMode').value,provider_api_url:$('#paymentProviderApiUrl')?.value||'',provider_payment_url:$('#paymentProviderPaymentUrl')?.value||'',provider_dashboard_url:$('#paymentProviderDashboardUrl')?.value||'',provider_help_url:$('#paymentProviderHelpUrl')?.value||'',sbp_enabled:$('#paymentSbpEnabled')?.checked!==false,yookassa_shop_id:$('#yookassaShopId')?.value||'',yookassa_secret_key:$('#yookassaSecretKey')?.value||'',yookassa_return_url:$('#yookassaReturnUrl')?.value||'',yookassa_webhook_url:$('#yookassaWebhookUrl')?.value||'',robokassa_merchant_login:$('#robokassaMerchantLogin')?.value||'',robokassa_password1:$('#robokassaPassword1')?.value||'',robokassa_password2:$('#robokassaPassword2')?.value||'',robokassa_result_url:$('#robokassaResultUrl')?.value||'',robokassa_success_url:$('#robokassaSuccessUrl')?.value||'',robokassa_fail_url:$('#robokassaFailUrl')?.value||'',robokassa_is_test:$('#robokassaIsTest')?.checked!==false,active:$('#paymentActive').checked};const result=await request('POST',payload);DATA.payment_settings=result.item||payload;renderPaymentSettings();toast('Payment settings saved');await load(sessionStorage.getItem('taxichi_admin_token'))}catch(err){toast(err.message)}};
  if($('#paymentSettingsSave'))$('#paymentSettingsSave').onclick=savePaymentSettings;
}


// Clean subscriptions/payment UI override.
function setProviderVisibilityClean(){
  const provider = document.querySelector('#paymentProvider')?.value || 'manual';
  document.querySelectorAll('.provider-manual').forEach(x => x.hidden = provider !== 'manual');
  document.querySelectorAll('.provider-yookassa').forEach(x => x.hidden = provider !== 'yookassa');
  document.querySelectorAll('.provider-robokassa').forEach(x => x.hidden = provider !== 'robokassa');
  const hints = {
    manual: 'СБП / ручная оплата: можно указать checkout-ссылку или подтверждать оплату вручную.',
    yookassa: 'YooKassa: заполните shopId, secret key, return_url и webhook URL.',
    robokassa: 'Robokassa: заполните MerchantLogin, Password #1/#2 и Result/Success/Fail URL.'
  };
  const state = document.querySelector('#paymentSettingsState');
  if (state) state.textContent = hints[provider] || '';
}

function renderPaymentSettingsClean(){
  const p = paymentSettings();
  const provider = ['manual','yookassa','robokassa'].includes(p.provider) ? p.provider : 'manual';
  const set = (id, value) => { const el = document.querySelector('#' + id); if (el) el.value = value ?? ''; };
  const check = (id, value) => { const el = document.querySelector('#' + id); if (el) el.checked = value !== false; };
  set('paymentProvider', provider);
  set('paymentProviderTitle', p.provider_title || (provider === 'manual' ? 'СБП / ручная оплата' : provider));
  set('paymentPrice', p.monthly_price_rub || 499);
  set('paymentDiscount', p.discount_percent ?? 20);
  set('paymentReferralPercent', p.referral_percent ?? 10);
  set('paymentPayoutMode', p.payout_mode || 'manual');
  set('paymentProviderPaymentUrl', p.provider_payment_url || '');
  set('yookassaShopId', p.yookassa_shop_id || '');
  set('yookassaSecretKey', p.yookassa_secret_key || '');
  set('yookassaReturnUrl', p.yookassa_return_url || '');
  set('yookassaWebhookUrl', p.yookassa_webhook_url || '');
  set('robokassaMerchantLogin', p.robokassa_merchant_login || '');
  set('robokassaPassword1', p.robokassa_password1 || '');
  set('robokassaPassword2', p.robokassa_password2 || '');
  set('robokassaResultUrl', p.robokassa_result_url || '');
  set('robokassaSuccessUrl', p.robokassa_success_url || '');
  set('robokassaFailUrl', p.robokassa_fail_url || '');
  check('paymentFullAccessForAll', p.full_access_for_all);
  check('paymentSbpEnabled', p.sbp_enabled);
  check('robokassaIsTest', p.robokassa_is_test);
  check('paymentActive', p.active);
  setProviderVisibilityClean();
}

async function savePaymentSettingsClean(){
  try {
    const payload = {
      action: 'payment_settings_save',
      provider: document.querySelector('#paymentProvider')?.value || 'manual',
      provider_title: document.querySelector('#paymentProviderTitle')?.value.trim() || '',
      monthly_price_rub: Number(document.querySelector('#paymentPrice')?.value || 499),
      discount_percent: Number(document.querySelector('#paymentDiscount')?.value || 0),
      referral_percent: Number(document.querySelector('#paymentReferralPercent')?.value || 10),
      payout_mode: document.querySelector('#paymentPayoutMode')?.value || 'manual',
      full_access_for_all: document.querySelector('#paymentFullAccessForAll')?.checked === true,
      provider_api_url: '',
      provider_payment_url: document.querySelector('#paymentProviderPaymentUrl')?.value || '',
      provider_dashboard_url: '',
      provider_help_url: '',
      sbp_enabled: document.querySelector('#paymentSbpEnabled')?.checked !== false,
      yookassa_shop_id: document.querySelector('#yookassaShopId')?.value || '',
      yookassa_secret_key: document.querySelector('#yookassaSecretKey')?.value || '',
      yookassa_return_url: document.querySelector('#yookassaReturnUrl')?.value || '',
      yookassa_webhook_url: document.querySelector('#yookassaWebhookUrl')?.value || '',
      robokassa_merchant_login: document.querySelector('#robokassaMerchantLogin')?.value || '',
      robokassa_password1: document.querySelector('#robokassaPassword1')?.value || '',
      robokassa_password2: document.querySelector('#robokassaPassword2')?.value || '',
      robokassa_result_url: document.querySelector('#robokassaResultUrl')?.value || '',
      robokassa_success_url: document.querySelector('#robokassaSuccessUrl')?.value || '',
      robokassa_fail_url: document.querySelector('#robokassaFailUrl')?.value || '',
      robokassa_is_test: document.querySelector('#robokassaIsTest')?.checked !== false,
      active: document.querySelector('#paymentActive')?.checked !== false
    };
    const result = await request('POST', payload);
    DATA.payment_settings = result.item || payload;
    renderPaymentSettingsClean();
    toast('Настройки оплаты сохранены');
    await load(sessionStorage.getItem('taxichi_admin_token'));
  } catch (err) {
    toast(err.message);
  }
}

renderPaymentSettings = renderPaymentSettingsClean;
savePaymentSettings = savePaymentSettingsClean;
document.querySelector('#paymentProvider')?.addEventListener('change', setProviderVisibilityClean);
document.querySelector('#paymentSettingsSave')?.addEventListener('click', savePaymentSettingsClean);
document.querySelector('#paymentSettingsSaveTop')?.addEventListener('click', savePaymentSettingsClean);

// --- Admin cabinet / manager access ---
const SECTION_LABELS={overview:'Обзор',users:'Водители',map:'Карта',subscriptions:'Подписки',referrals:'Рефералы',leaderboard:'Конкурс',chat:'Чат',newsletter:'Рассылка',partners:'Партнёры',system:'Система',cabinet:'Кабинет'};
let ADMIN=null;
titles.cabinet='Кабинет';
function adminSections(){return ADMIN?.sections?.length?ADMIN.sections:['overview','users','map','subscriptions','referrals','leaderboard','chat','newsletter','partners','system','cabinet']}
function canSection(id){return ADMIN?.role==='owner'||adminSections().includes(id)}
function firstAllowed(){return adminSections().find(x=>x!=='cabinet'||ADMIN?.role==='owner')||'overview'}
function applyAdminPermissions(){
  ADMIN=DATA?.admin_current||ADMIN;
  all('.nav').forEach(btn=>{const id=btn.dataset.page;btn.hidden=!canSection(id)||(id==='cabinet'&&ADMIN?.role!=='owner')});
  if(ADMIN?.role!=='owner') all('.owner-only').forEach(x=>x.hidden=true); else all('.owner-only').forEach(x=>x.hidden=false);
  const active=document.querySelector('.page.active-page')?.id;
  if(active&&!canSection(active)) page(firstAllowed());
  wireOverviewCards();
}
const basePage=page;
page=function(id){if(!canSection(id)){toast('Нет доступа к этому разделу');id=firstAllowed()}basePage(id);if(id==='cabinet')renderCabinet()}
const baseRender=render;
render=function(){baseRender();ADMIN=DATA?.admin_current||ADMIN;applyAdminPermissions();renderCabinet();wireAccessButtons()}
$('#loginButton').onclick=async()=>{
  const login=$('#adminLogin')?.value.trim(),password=$('#adminPassword')?.value;
  if(!login||!password){$('#loginError').textContent='Введите логин и пароль';return}
  try{
    const response=await fetch(`${cfg.supabaseUrl}/functions/v1/admin-stats`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'admin_login',login,password})});
    if(!response.ok)throw new Error(response.status===401?'Неверный логин или пароль':'Ошибка входа');
    const data=await response.json();ADMIN=data.admin;sessionStorage.setItem('taxichi_admin_token',data.token);await load(data.token);
  }catch(err){$('#loginError').textContent=err.message}
};
$('#adminPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginButton').click()});
$('#adminLogin')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginButton').click()});
$('#resetPasswordButton')&&($('#resetPasswordButton').onclick=()=>{$('#loginError').textContent='Для сброса пароля обратитесь к владельцу или смените пароль в Кабинете.'});
$('#refresh').onclick=()=>load(sessionStorage.getItem('taxichi_admin_token'));
function renderCabinetSections(selected=[]){
  const box=$('#cabinetSections'); if(!box)return;
  box.innerHTML=Object.entries(SECTION_LABELS).filter(([id])=>id!=='cabinet').map(([id,label])=>`<label class="cabinet-check"><input type="checkbox" value="${id}" ${selected.includes(id)?'checked':''}>${label}</label>`).join('');
}
function resetCabinetForm(){
  if(!$('#cabinetAdminId'))return;
  $('#cabinetAdminId').value='';$('#cabinetEmail').value='';$('#cabinetLogin').value='';$('#cabinetPassword').value='';$('#cabinetRole').value='manager';$('#cabinetActive').checked=true;renderCabinetSections(['overview','users','subscriptions','partners','chat']);
}
function renderCabinet(){
  if(!$('#cabinet'))return;
  if(!ADMIN)ADMIN=DATA?.admin_current;
  $('#cabinetRoleBadge')&&( $('#cabinetRoleBadge').textContent=ADMIN?.role==='owner'?'Владелец':'Менеджер' );
  if(!$('#cabinetSections input'))renderCabinetSections(['overview','users','subscriptions','partners','chat']);
  const users=DATA?.admin_users||[];
  $('#cabinetCount')&&( $('#cabinetCount').textContent=`${users.length} пользователей` );
  if($('#cabinetUsers')) $('#cabinetUsers').innerHTML=users.map(u=>`<div class="cabinet-user ${u.active?'':'off'}"><div class="avatar">${initial(u.login)}</div><div class="grow"><b>${e(u.login)} · ${e(u.role)}</b><span>${e(u.email)} · ${u.active?'активен':'отключён'} · ${u.last_login_at?date(u.last_login_at):'ещё не входил'}</span><small>${(u.sections||[]).map(x=>SECTION_LABELS[x]||x).join(', ')}</small></div><button class="ghost" onclick='editAdminUser(${JSON.stringify(u).replace(/'/g,"&#39;")})'>Изменить</button>${u.id!==ADMIN?.id?`<button class="${u.active?'danger':'success'}" onclick="toggleAdminUser('${u.id}',${!u.active})">${u.active?'Отключить':'Включить'}</button>`:''}</div>`).join('')||empty('Пользователей пока нет');
}
window.editAdminUser=function(u){$('#cabinetAdminId').value=u.id;$('#cabinetEmail').value=u.email||'';$('#cabinetLogin').value=u.login||'';$('#cabinetPassword').value='';$('#cabinetRole').value=u.role||'manager';$('#cabinetActive').checked=u.active!==false;renderCabinetSections(u.sections||[]);page('cabinet')}
async function saveAdminUser(){
  const sections=all('#cabinetSections input:checked').map(x=>x.value);
  await action({action:'admin_user_save',id:$('#cabinetAdminId').value,email:$('#cabinetEmail').value,login:$('#cabinetLogin').value,password:$('#cabinetPassword').value,role:$('#cabinetRole').value,active:$('#cabinetActive').checked,sections});
  resetCabinetForm();
}
window.toggleAdminUser=async(id,active)=>{if(confirm(active?'Включить менеджера?':'Отключить менеджера?'))await action({action:'admin_user_toggle',id,active})}
$('#cabinetSave')&&($('#cabinetSave').onclick=saveAdminUser);
$('#cabinetReset')&&($('#cabinetReset').onclick=resetCabinetForm);
$('#cabinetMyPasswordSave')&&($('#cabinetMyPasswordSave').onclick=async()=>{const password=$('#cabinetMyPassword').value;if(password.length<6)return toast('Пароль минимум 6 символов');await action({action:'admin_password_change',password});$('#cabinetMyPassword').value='';toast('Пароль изменён')});
resetCabinetForm();
function wireOverviewCards(){
  const cards=all('#metrics .metric');
  const routes=['users','users','subscriptions','subscriptions','users','users','users','subscriptions'];
  cards.forEach((card,i)=>{card.classList.add('clickable-metric');card.onclick=()=>page(routes[i]||'users')});
}
function paymentPayloadWithAccess(fullAccess){
  const p=DATA?.payment_settings||{};
  return {action:'payment_settings_save',provider:p.provider||'manual',provider_title:p.provider_title||'СБП / ручная оплата',monthly_price_rub:Number(p.monthly_price_rub||499),discount_percent:Number(p.discount_percent||20),referral_percent:Number(p.referral_percent||10),payout_mode:p.payout_mode||'manual',full_access_for_all:fullAccess,provider_api_url:p.provider_api_url||'',provider_payment_url:p.provider_payment_url||'',provider_dashboard_url:p.provider_dashboard_url||'',provider_help_url:p.provider_help_url||'',sbp_enabled:p.sbp_enabled!==false,yookassa_shop_id:p.yookassa_shop_id||'',yookassa_secret_key:'__KEEP_SECRET__',yookassa_return_url:p.yookassa_return_url||'',yookassa_webhook_url:p.yookassa_webhook_url||'',robokassa_merchant_login:p.robokassa_merchant_login||'',robokassa_password1:'__KEEP_SECRET__',robokassa_password2:'__KEEP_SECRET__',robokassa_result_url:p.robokassa_result_url||'',robokassa_success_url:p.robokassa_success_url||'',robokassa_fail_url:p.robokassa_fail_url||'',robokassa_is_test:p.robokassa_is_test!==false,active:p.active!==false};
}
async function setFullAccessForAll(fullAccess){
  const ok = await accessConfirm(fullAccess);
  if(!ok)return;
  await request('POST',paymentPayloadWithAccess(fullAccess));
  toast(fullAccess?'Полный доступ открыт всем':'Бесплатный доступ закрыт');
  await load(sessionStorage.getItem('taxichi_admin_token'));
  page('users');
}
function accessConfirm(fullAccess){
  return new Promise(resolve=>{
    const old=document.querySelector('#accessConfirmModal'); old?.remove();
    const modal=document.createElement('div');
    modal.id='accessConfirmModal';
    modal.className='access-confirm-modal';
    modal.innerHTML=`<div class="access-confirm-backdrop"></div><article class="access-confirm-card">
      <div class="access-confirm-icon">${fullAccess?'✓':'!'}</div>
      <h2>${fullAccess?'Открыть полный доступ всем?':'Закрыть бесплатный доступ?'}</h2>
      <p>${fullAccess?'Все водители смогут пользоваться Premium-разделами без оплаты. Это удобно для теста или акции.':'Доступ закроется у всех, кто не купил Premium. У водителей с активной подпиской доступ останется.'}</p>
      <div class="access-confirm-actions">
        <button class="ghost" data-access-cancel>Отмена</button>
        <button class="${fullAccess?'success':'danger'}" data-access-ok>${fullAccess?'Открыть всем':'Закрыть бесплатный'}</button>
      </div>
    </article>`;
    document.body.appendChild(modal);
    const done=value=>{modal.remove();resolve(value)};
    modal.querySelector('[data-access-cancel]').onclick=()=>done(false);
    modal.querySelector('.access-confirm-backdrop').onclick=()=>done(false);
    modal.querySelector('[data-access-ok]').onclick=()=>done(true);
  });
}
function wireAccessButtons(){
  const open=$('#openFullAccessAll'),close=$('#closeFreeAccessAll');
  if(open&&!open.dataset.ready){open.dataset.ready='1';open.onclick=()=>setFullAccessForAll(true)}
  if(close&&!close.dataset.ready){close.dataset.ready='1';close.onclick=()=>setFullAccessForAll(false)}
}
